### PR TITLE
Move `tokio_io::codec::length_delimited` module to `tokio::codec`

### PR DESCRIPTION
**Pull request by hawkw**
In preparation for additional work on issue  #500, this branch moves the
`length_delimited` module from the `tokio-io` crate to the `tokio` crate's
`codec` module To avoid a breaking change, the current code is left in 
place, but it has been deprecated and hidden from the docs.

Refs: #500

### CODE REVIEW

**Comment by hawkw** [comment]
The AppVeyor build failure for 5be4b0efc86e03163819356f553fdafd11c96040 seems unrelated --- looks like a (presumably transient) failure downloading dependencies.

**Comment by tobz** [comment]
I'm not sure if you have repo write perms; if not, just cc me here or on gitter and I can trigger the merge when you think docs/tests are all gravy. 👍

**Comment by carllerche** [comment]
@hawkw the appveyor failure was unrelated (should be fixed now) but it looks like there is also a failure when building w/ Rust 1.25. Would you mind taking a look?

**Comment by hawkw** [comment]
@carllerche Yeah, @tobz and I were discussing that on Gitter, it seems like the doctests are somehow breaking the Rust 1.25.0 build. I'll try to figure that out.

**Comment by hawkw** [comment]
4704be05fb8e904e91c8b725f973749ff49776df fixes the Rust 1.25 build, so this should be mergeable when CI passes.

**Comment by tobz** [comment]
Hooray!

**Pull request merged**
