### PR TITLE
macros: fix mut patterns in `select!` macro

### PR DESCRIPTION
**Pull request by Darksonn**
Closes: #4182
Closes: #4076

### CODE REVIEW

**Comment by Darksonn** [comment]
I am rather confident that this cannot be done without a new proc-macro. I spent some time trying to restructure the macro to avoid matching twice, but I was unable to because we need the `futures` variable to go out of scope before the success handlers run.

**Comment by carllerche** [comment]
I'll take a look. We probably want @taiki-e to 👀 at it as well.

**Comment by carllerche** [comment]
@Darksonn is there a downside for the user to a new proc macro?

**Review by carllerche — APPROVED** [review]
Looks fine to me. I would love it if @taiki-e could take a glance, but nothing stands out to me.

**Review by taiki-e — APPROVED** [review]
LGTM

**Pull request merged**
