### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by jimman2003**
## Motivation
Saw multiple commits updating deps
Maybe lighten the work needed

## Solution
Add dependabot

### CODE REVIEW

**Comment by Darksonn** [comment]
We don't actually want to automatically require the latest version of every dependency. That imposes a stronger requirement on people using Tokio than we need to.

**Comment by jimman2003** [comment]
there is allowed_updates...https://dependabot.com/docs/config-file/#allowed_updates

**Comment by jimman2003** [comment]
In another PR sb can restrict the updates

**Comment by Darksonn** [comment]
I am closing this. We will increase the required version of dependencies when we use a feature of a newer version of the dependency, and we already have something in our CI setup to detect security issues.

**Pull request closed without merging**
