### PR TITLE
Avoid taking a lock in `PollEvented::poll_ready` 

### PR DESCRIPTION
**Pull request by alexcrichton**
This function is the source of all readiness notifications (and polling) in
`PollEvented`. Currently, however, it'll bounce on an rwlock (in read mode),
which can often cause performance degredation across platforms.

This commit instead alters the logic to avoid hitting a lock in `poll_ready`
entirely. This is achieve by storing `Arc<ScheduledIo>`, the allocated state for
each I/O object, inside the I/O objects directly. Previously only an index
(`token: usize`) was stored which meant that the original slab had to be
reindexed (and locked) each time an I/O object needed to look up its state.

This does come at the cost of a forced allocation per I/O object, but that was
effectively already happening in the previous iteration with allocation space in
the slab. If this ends up becoming a problem then we can always look into
caching mechanisms as well for `Arc<ScheduledIo>` and have a slab of free
versions on the reactor.

> **Note**: This PR is based on https://github.com/tokio-rs/tokio/pull/83, only the last commit needs reviewing.

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for looking into this.

I'd personally rather wait until we are close to feature complete, and then take a more analytical approach to performance optimizations.

First, while I am with you on your intuition that a global lock is sub optimal, I'd like to see some numbers and benchmarks included. Also, I'd like to think through the implications of the various strategies for improving performance. While the proposed change is most likely good for the general case, allocations should not be needed in cases where the slab can be preallocated.

I also think there are probably other strategies that can be explored that don't incur the forced allocation per resource.

**Comment by cramertj** [comment]
FWIW this is exactly how the `PacketReceiver` interface works in the Fuchsia fork, and making this change would reduce the diff between the two approaches.

**Comment by alexcrichton** [comment]
I'm having a surprisingly hard time getting a profile where lock contention is dominant, so let's put this on the backburner!

**Comment by carllerche** [comment]
Well, it's not like performance matters anymore post meltdown / spectre remediation.

**Pull request closed without merging**
