### PR TITLE
fs: fallback implementation that doesn't rely on `blocking()`

### PR DESCRIPTION
**Pull request by stjepang**
## Summary

Make `tokio-fs` work on runtimes that don't have `tokio-threadpool`.

Apologies for the big PR. :( While the total diff is pretty large, half of it
is just boring boilerplate. You can find the most interesting code in these
files:

* `fallback.rs`
* `blocking_pool.rs`

## Motivation

When using the `curent-thread` runtime, the `tokio_threadpool::blocking()`
function is not available, which is currently a requirement for `tokio-fs` to
to run blocking filesystem operations.

Note that `tokio-current-thread` cannot implement a function equivalent to
`tokio_threadpool::blocking()` because futures in this single-threaded
executor are not necessarily `Send`. That means we cannot start executing
the blocking function on the current thread and move the event loop onto a
new thread.

Blocking filesystem operations therefore *must* be run on a thread different
from the current one. Still, the solution to this problem is not as easy as
"just" spawning blocking operations onto a different thread.

## Naive solutions and why they don't work

Consider this function that reads bytes from a file asynchronously:

```rust
pub fn poll_read(&mut self, buf: &mut [u8]) -> Poll<usize, io::Error> {
    // ...
}
```

Suppose now that the file is not ready for reading and spawns a blocking
operation onto a different thread. Where should the read bytes be written? We
can't write them into `buf` because this reference is not available after
`poll_read()` returns `Ok(Async::NotReady)`.

A solution might be to change the signature of the function so that it gives
the `poll_read()` function a buffer, moves it into the spawned blocking task,
and finally returns it back when ready:

```rust
pub fn poll_read(&mut self, buf: Vec<u8>) -> Poll<Vec<u8>, io::Error> {
    // ...
}
```

This would work just fine at the expense of having a more cumbersome interface
and not being able to implement the `AsyncRead` trait.

## The right solution

Fortunately, there is a way out of this mess. We can create a hidden internal
byte buffer inside our file implementation. When `poll_read()` gets called,
we transfer bytes from the internal buffer into `buf`. And if the buffer is
empty, we spawn a blocking operation that reads from the file and refills
the internal buffer.

This is a neat solution, but note that it complicates other operations, too.
For example, if we want to seek inside the file 100 bytes forward but the
buffer is 10 bytes long, that means we *actually* need to seek 90 bytes forward
only because the cursor has already been moved 10 bytes forward by the last
async read operation.

Long story short, if we keep building the whole set of async file operations
this way, we'll essentially reimplement the same file abstraction that exists
inside the OS when a file is opened. There will be a read/write buffer, some
sort of state like the current position inside the file, whether there is data
that needs to be flushed to disk, etc.

## What's in this PR?

First, function `entered()` that returns a `bool` is added to
`tokio-threadpool` so that we can check whether `blocking()` is available or
not.

Then, there is a very simple "blocking pool" implementation that is able to
spawn tasks that execute blocking functions. It is currently just a hack on
top of a dedicated `tokio-threadpool` instance and will need a better
implementation in the future. See #588.

Simple filesystem operations like `remove_file()` just call `entered()` and
then call the blocking operation inside `blocking()` if available, or else
spawn the operation onto the blocking pool and await its result.

The whole `tokio-fs` crate besides stdin/stdout/stderr is covered by this PR.

Implementing `tokio_fs::File` was the biggest challenge by far because we
need to keep a pretty complex state of the file and make transitions through
its state machine when async operations get polled.

The fallback implementation of `File` is inside `fallback.rs`. The general
idea behind its design is that there is an `Option<State>` (set to `None` when
the file is closed) containing the state of the file, which consists of:

1. The file handle of type `std::fs::File`.
2. The byte buffer - essentially a `Vec<u8>` and a slice inside it.
3. Whether the buffer is currently used for reading or writing.
4. The result of the last async operation.

The file is either idle and contains the state, or blocked on an async
operation and contains just an awaitable handle to the operation. When the
async operation is completed, it returns back the state and the file becomes
idle again. There can be only one async operation in progress at a time.

As an example, function `poll_read()` will do the following:

1. If the last operation was read and resulted in EOF, return.
2. If the buffer is currently used for writing, spawn an operation flushing it.
3. If the buffer is empty, spawn an operation that reads from the file and
   refills the buffer.
4. Otherwise, the buffer is ready for reading so we can just pull some bytes
   from it.

## Backwards compatibility

Unfortunately, we have to break compatibility in a few cases. Consider this
function:

```rust
pub fn create_dir<P: AsRef<Path>>(path: P) -> CreateDirFuture<P> {
    // ...
}
```

We cannot spawn a blocking task that runs `std::fs::create_dir(path)` onto a
different thread because `P` is not `Send + 'static`. Therefore, we need
this signature instead:

```rust
pub fn create_dir(path: P) -> CreateDirFuture<P>
where
    P: AsRef<Path> + Send + 'static,
{
    // ...
}
```

Here's a complete list of functions that break compatibility in the same
manner:

- `create_dir(path)`
- `create_dir_all(path)`
- `hard_link(src, dist)`
- `symlink(src, dist)`
- `symlink_dir(src, dist)`
- `symlink_file(src, dist)`
- `read_link(path)`
- `remove_dir(path)`
- `remove_file(path)`
- `rename(from, to)`
- `set_permissions(path, perm)`

## Additional notes and caveats

* The fallback `File` implementation wraps its inner representation into an
  `Arc<Mutex<_>>` and every operation on the file locks the mutex. The reason
  why we do that is because `File` handles can be cloned and shared among
  threads. But that's totally okay - OS-level file descriptors can be cloned
  (aka "duped") as well so the OS will protect the internal file state by
  its equivalent of `Arc<Mutex<_>>` too.

* If you don't flush or close the file manually, the contents written into the
  file might be lost! Unfortunately, we cannot (actually, *can* but probably
  *shouldn't*) flush the contents when `File` gets dropped because flushing is
  a blocking operation.

* Functions [`poll_metadata()`] and [`poll_file_type()`] should've taken
  `&mut self` rather than `&self`. We could switch to `&mut self` and break
  compatibility, but I decided to just wrap the inner state of `DirEntry`
  inside a mutex instead.

* The async function `write(path, contents)` will now also flush after writing
  into the file. I figured it'd be too easy to make mistakes without
  automatic flushing and in fact, without flushing one of the tests was
  failing.

* Performance is not good right now. For example, reading a 10 Gb file
  currently takes ~10 times longer using the fallback method. But don't worry,
  there is a way to bring the implementation on par with blocking file reads
  (or maybe make it even faster?). See below under "remaining work".

* In #954, @carllerche asked about unnecessary allocations during blocking
  task spawning. The current blocking pool based on `tokio-threadpool` is
  very simple and not really designed for performance. Once we build a proper
  `tokio-blocking` pool, spawning will incur a single allocation only.

* Since `tokio-fs` expects `tokio_threadpool::entered()`, we'll temporarily
  need a `[patch.crates-io]` section inside `Cargo.toml` to use the local
  version of `tokio-threadpool` rather than the latest published one.

[`poll_metadata()`]: https://docs.rs/tokio-fs/0.1.6/tokio_fs/struct.DirEntry.html#method.poll_metadata
[`poll_file_type()`]: https://docs.rs/tokio-fs/0.1.6/tokio_fs/struct.DirEntry.html#method.poll_file_type

## Tests

The test suite has been refactored so that all unit tests get run on both
runtimes (the one based on `tokio-threadpool` and the one based on
`tokio-current-thread`).

All tests seem to be passing, but note that the test suite is not as
extensive at the moment as we would like it to be. There's a lot of functions
that are simply not covered by tests.

## Remaining work

There is some remaining work, but I'd like to address it in seprate PRs:

* The test suite needs higher coverage. Nothing besides the most important
  filesystem operations is currently tested.

* Instead of the simple blocking pool hack inside `blocking_pool.rs`, we'll
  need a real thread pool for executing blocking functions. This issue is
  tracked in #588.

* Support for stdin/stdout/stderr will come later. Reading/writing from/into
  these files is a slightly different problem because operations on them
  might block for a longer time than typical filesystem operations, or might
  even block indefinitely waiting for user input.

* Performance improvements. Increasing the size of the internal buffer seems
  to make huge reads much faster, so we probably just need to tweak the buffer
  growth or prefetching strategy. There is an [article] on readahead logic in
  the Linux kernel we might want to steal ideas from.

[article]: https://lwn.net/Articles/372384/

Refs: #1178

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for the very detailed PR message. I am still in the process of reviewing, but I am excited about the changes.

At a high level, I agree that we should try to land this incrementally. I would like to discuss the plan a bit more. The goal of master is to always be in a state to publish to crates.io.

I wonder if, initially we could avoid breaking changes. Could the functions that take `P: AsRef<Path>` clone the `Path` in order to avoid making the argument `Send + 'static`?

Second, it looks like the `tokio-fs` APIs will *always* use the fallback. The eventual goal would be to tie the blocking pool to the runtime (similar to the net APIs & tokio-reactor). If we merge & release this PR, it would become a breaking change to transition to a runtime blocking pool as callers are able to assume a blocking pool is always available (via lazy static). Do you have thoughts on how to mitigate this? One option (not sure how good) would be to require the user to opt into experimental functionality via feature flag or env var.

More feedback is coming.

**Comment by carllerche** [comment]
> The reason why we do that is because `File` handles can be cloned and shared among threads. 

Regarding the public interface, I don't think `File` can impl `Clone`. We would want to provide a `dup` API, but I believe that could fail.

**Comment by stjepang** [comment]
> I wonder if, initially we could avoid breaking changes. Could the functions that take `P: AsRef<Path>` clone the `Path` in order to avoid making the argument `Send + 'static`?

Unfortunately, I don't see a way out of that. :( It seems not requiring `Send + 'static` on those functions was a mistake we cannot fix without breaking compatibility. As a temporary measure before releasing 0.2, we could panic in those functions if `tokio-threadpool` is not being used.

> Second, it looks like the `tokio-fs` APIs will _always_ use the fallback.

I'm not sure what you mean by this? As can be seen [here](https://github.com/tokio-rs/tokio/blob/16c7b72bad62f0ad55692c0f545a609018379d59/tokio-fs/src/file/open.rs#L26) for example, we're using fallback only if `tokio_threadpool::entered()` returns `false`.

> Regarding the public interface, I don't think `File` can impl `Clone`. We would want to provide a `dup` API, but I believe that could fail.

But [`tokio_fs::File::try_clone()`](https://docs.rs/tokio-fs/0.1.6/tokio_fs/file/struct.File.html#method.try_clone) currently exists. Are you suggesting we deprecate and eventually remove this method? Should this method always return an error in the fallback mode?

**Comment by stjepang** [comment]
I've changed the behavior of `poll_seek()` to make it more consistent and added a comment explaining why it's implemented that way.

The short story is, we want `poll_seek()` to actually move the cursor if and only if `Ready(Ok(_))` is returned by the function.

**Comment by stjepang** [comment]
I've resolved merge conflicts. Would the addition of `Send + 'static` bounds be acceptable now that we're making breaking changes for Tokio 0.2?

**Comment by carllerche** [comment]
Closing due to inactivity.

**Pull request closed without merging**
