### PR TITLE
Enable cfg_fs for wasi

### PR DESCRIPTION
**Pull request by namse**
## Motivation

We are currently using `wasip1-threads` and have implemented our own `wasi fs`. However, there is a restriction that prevents using the file system feature when `cfg_fs` is set to `wasi`. I believe this restriction should be lifted, as it contradicts the intention stated in the Tokio code, where enabling the `tokio_unstable` flag allows the use of the file system feature ([relevant code link](https://github.com/tokio-rs/tokio/blob/1166ecc2accc1a4bab47612858e7166617d15cfe/tokio/src/lib.rs#L465)).

## Solution

I have removed the `wasi` condition from `cfg_fs` to enable the file system feature. After forking Tokio and applying this change, I tested it and found that it works perfectly. This change will allow support for the file system feature in the `wasip1-threads` environment.

### CODE REVIEW

**Comment by namse** [comment]
Is there a maintainer who can review this PR? Our team primarily uses WASI, but this issue is a major obstacle in using Tokio with WASI. We would greatly appreciate any help.

**Comment by Darksonn** [comment]
I believe that this was added because `std::fs` relies on `spawn_blocking` but wasm is single-threaded. I understand that the threading situation has improved recently. Are you able to confirm that this actually works?

**Comment by namse** [comment]
Yes, this works well. I've already forked Tokio and am using the modified PR to use Tokio FS in a web browser, with web-worker based multi threading. However, I decided to create a PR because continuing to use the forked version could cause compatibility issues with other crates.

Not all WASM, or more specifically WASI, is single-threaded. Among Rust targets, there are `wasm32-wasip1`, `wasm32-wasip1-thread`, and `wasm32-wasip2`. `wasm32-wasip1` does not support threads, but `wasm32-wasip1-thread` supports pthread-style threading. As for `wasip2`, I'm not entirely sure.

WASI support in Tokio is already experimental. Since WASI itself is such an experimental project, I believe most WASI users will check whether their WASI runtime implementation supports threads or not(most of major runtimes support threads). Therefore, I don't think there will be any major issues in enabling the configuration to allow using Tokio FS in thread-supporting WASI environments.

**Comment by Darksonn** [comment]
Ok, I don't mind adding this. There's a compilation failure, though.

https://github.com/tokio-rs/tokio/blob/91169992b2ed0cf8844dbaa0b4024f9db588a629/tokio/src/fs/open_options.rs#L396-L399

We can fix it like this:
```rs
/// Returns a mutable reference to the underlying `std::fs::OpenOptions`
#[cfg(any(windows, unix))]
pub(super) fn as_inner_mut(&mut self) -> &mut StdOpenOptions {
    &mut self.0
}
```

**Comment by namse** [comment]
If the compile error is due to the function not being used in WASI, would it be okay to include a fix for that in this PR as well? 

It might be a good idea for me to modify the PR to ensure there are no compile errors overall and then request a review from you.

**Comment by Darksonn** [comment]
Go ahead.

**Comment by namse** [comment]
I thought I would need more changes, but it's not. There's nothing more except for the modifications you mentioned. Please check.

**Review by Darksonn — APPROVED** [review]
Thank you.

**Comment by namse** [comment]
Github Action Canceled https://github.com/tokio-rs/tokio/actions/runs/10803632984/job/29967823508?pr=6822
What should I do?

**Comment by Darksonn** [comment]
You don't need to do anything. I will rerun.

**Comment by namse** [comment]
@Darksonn If it's not too much trouble, may I ask when this change is expected to be released?

**Comment by Darksonn** [comment]
We don't have very many changes since the last release, so it may be another month. But if you are willing to do the work of preparing the release, we can make one now.

**Comment by namse** [comment]
After reviewing this document (https://github.com/tokio-rs/tokio/blob/master/CONTRIBUTING.md#releasing), I believe I can handle it. I have some other tasks to finish first, but once I'm done, I'll create a PR for the release.

**Pull request merged**
