### PR TITLE
Remove beta from CI run

### PR DESCRIPTION
**Pull request by carllerche**
It is failing w/ the error that beta is not available.

### CODE REVIEW

**Comment by seanmonstar** [comment]
It seems better to run on beta ...

**Comment by seanmonstar** [comment]
Restarting the job doesn't fix it?

**Comment by carllerche** [comment]
I tried a couple of times :-/

**Comment by seanmonstar** [comment]
Seems fine then.

**Comment by carllerche** [comment]
Seems like the issue passed...

**Pull request closed without merging**
