### PR TITLE
Update as the `tokio` crate

### PR DESCRIPTION
**Pull request by alexcrichton**
This is currently a work in progress and represents the last state I had on the branch here, I haven't had a chance to clean it up or update it to the current state of the RFC, but I can do so in the near future!

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @carllerche @aturon 

I'll try to soon send a PR to tokio-core to use this new crate as well so we can see what that looks like.

**Comment by carllerche** [comment]
Thanks for setting this up.

This will be a pretty large set of changes. I would find it easiest to break down the PRs to incremental changes to make it easier to understand the diff and review.

I know you are currently at a conference, so I setup an initial two PRs to import the tokio-core history and to rename the crate + delete deprecated code.

#17, #18

**Comment by carllerche** [comment]
After the PRs above, I think that the next incremental change that makes sense is unifying `Remote` and `Handle`.

**Comment by carllerche** [comment]
This PR has been abandoned in favor for all the other PRs that have since landed. I am going to close this now.

**Pull request closed without merging**
