### PR TITLE
See if we can update :)

### PR DESCRIPTION
**Pull request by LucioFranco**

### CODE REVIEW

**Comment by taiki-e** [comment]
@LucioFranco I think this blocked on https://github.com/rust-lang/rust/pull/63316

**Comment by LucioFranco** [comment]
@taiki-e ah yup just checked the toolchain state, we can wait. I assume we will publish the alphas on futures alpha 17 with old nightly. Then we can release another with those both updated, does that sound like a good plan to you?

Gonna close this.

**Comment by taiki-e** [comment]
I think https://github.com/rust-lang-nursery/futures-rs/pull/1676 is the only change that affects tokio at now. However, if https://github.com/rust-lang-nursery/futures-rs/pull/1753  merged, publish the alphas will be blocked on rust-lang/rust#63316 (https://github.com/rust-lang-nursery/futures-rs/pull/1753 increases the minimum required nightly version of futures-preview to 2019-07-29.).

**Comment by LucioFranco** [comment]
@taiki-e yeah, I think those things we can support in the next alpha. So I think we will ship with 17 support today and the current toolchain. Then 18 we can update to new futures release and a newer version of rustc/rustfmt.

**Pull request closed without merging**
