### PR TITLE
feat(util): impl listener for either

### LINKED ISSUE #6201: Implement Listener for Either
The tokio-util crate has a type called [`Either`][2] for handling the case where you have one of two possible types. It implements various IO traits, but currently not the [`Listener`][1] trait.

To close this issue, add an implementation of the `Listener` trait for `Either`.

[1]: https://docs.rs/tokio-util/latest/tokio_util/net/trait.Listener.html
[2]: https://docs.rs/tokio-util/latest/tokio_util/either/enum.Either.html

### PR DESCRIPTION
**Pull request by saiintbrisson**
Implements the `Listener` trait for `Either`. This will ease
adding support for features such as #5678. Allowing users
to accept sockets from any of the two underlying listener
types, like `Either<UnixListener, TcpListener>`.

Closes #6201.

### CODE REVIEW

**Comment by Darksonn** [comment]
Hmm, I didn't realize that we already have non-trait methods for this.

This makes it more tricky because we shouldn't introduce a breaking change.

**Comment by saiintbrisson** [comment]
Indeed more tricky, but that was my reasoning behind leaving the original methods. `local_addr` remains with the same interface, and `accept` still has an equivalent future and output, unless there's something I'm not seeing.

Probably consider introducing a deprecation notice for `local_addr`?

**Comment by Darksonn** [comment]
Actually, this does change the return type of `accept` from `Result<Either<(L::Io, L::Addr), (R::Io, R::Addr)>>` to `Result<(Either<L::Io, R::Io>, Either<L::Addr, R::Addr>)>`.

**Comment by Darksonn** [comment]
I'm sorry, but I'm going to close this due to the existing methods.

Sorry for not double-checking this before opening the issue.

**Pull request closed without merging**
