### PR TITLE
Prepare 0.2.23 release

### PR DESCRIPTION
**Pull request by Darksonn**
# 0.2.23 (November 11, 2020)

### Fixes

 - time: report correct error for timers that exceed max duration (#2023)
 - time: fix resetting expired timers causing panics (#2587)
 - macros: silence `unreachable_code` warning in `select!` (#2678)
 - rt: fix potential leak during runtime shutdown (#2649)
 - sync: fix missing notification during mpsc close (#2854)

### Changes

 - io: always re-export `std::io` (#2606)
 - dependencies: update `parking_lot` dependency to 0.11.0 (#2676)
 - io: rewrite `read_to_end` and `read_to_string` (#2560)
 - coop: reset coop budget when blocking in `block_on` (#2711)
 - sync: better Debug for Mutex (#2725)
 - net: make `UnixListener::poll_accept` public (#2880)
 - dep: raise `lazy_static` to `1.4.0` (#3132)
 - dep: raise `slab` to `0.4.2` (#3132)

### Added

 - io: add `io::duplex()` as bidirectional reader/writer (#2661)
 - net: introduce split and `into_split` on `UnixDatagram` (#2557)
 - net: ensure that unix sockets have both `split` and `into_split` (#2687)
 - net: add `try_recv`/`from` & `try_send`/`to` to UnixDatagram (#1677)
 - net: Add `UdpSocket::{try_send,try_send_to}` methods (#1979)
 - net: implement `ToSocketAddrs` for `(String, u16)` (#2724)
 - io: add `ReaderStream` (#2714)
 - sync: implement map methods (#2771)

Closes: #3111

### CODE REVIEW

**Comment by Darksonn** [comment]
Do we need a tokio-macros release too?
```text
error: the async keyword is missing from the function declaration
 --> tokio/tests/macros_test.rs:4:7
  |
4 | async fn test_macro_can_be_used_via_use() {
  |       ^^

error: the async keyword is missing from the function declaration
  --> tokio/tests/macros_test.rs:13:7
   |
13 | async fn test_macro_is_resilient_to_shadowing() {
   |       ^^
```

**Comment by carllerche** [comment]
Might need one? were there changes?

**Comment by carllerche** [comment]
It looks highly likely we need to push out a macros release first.

**Comment by Darksonn** [comment]
tokio-macros release in #3127

**Comment by Darksonn** [comment]
We should include #3132 in this.

**Review by carllerche — APPROVED** [review]

**Pull request merged**
