### PR TITLE
Keep track of initialized bytes in read_to_end

### PR DESCRIPTION
**Pull request by Darksonn**
This keeps track of the number of initialized bytes inside `read_to_end`.

Note that old implementation is actually unsound as replacing the buffer inside `ReadBuf` does not require unsafe, and it does not check whether the pointer has been changed.
```Rust
// This should no longer even be possible in safe Rust. An implementor
// would need to have unsafely *replaced* the buffer inside `ReadBuf`,
// which... yolo?
assert!(new_len <= buf.capacity());
```

### CODE REVIEW

**Review by carllerche — APPROVED** [review]

**Comment by carllerche** [comment]
We probably want to wait for #3428 to get merged into master before merging this.

**Review by carllerche — APPROVED** [review]
Thanks

**Comment by vitalyd** [comment]
@Darksonn a small suggestion for `VecWithInitialized<V>`: use a sealed trait to constrain `V` to be a `Vec<u8>` or `&mut Vec<u8>`.  As it's written now, `VecWithInitialized::new` is unsafe because it requires `V` to be one of those 2 types, but the generic is constrained to just `V: AsMut<Vec<u8>>`.

Perhaps a formulation like the following would be better:
```
mod private {
   pub trait VecU8: AsMut<Vec<u8>> {} // better name welcome

   impl VecU8 for Vec<u8> {}
   impl VecU8 for &mut Vec<u8> {}
}

pub struct VecWithInitialized<V: VecU8> { ... }
```
Just an idea in passing ... :smile:

**Comment by Darksonn** [comment]
Feel free to submit a PR with that!

**Comment by vitalyd** [comment]
Ok, let me try to find a bit of time to do that :grin:.  Mostly wanted to run that by you in case you considered and rejected the idea for some reason.

**Pull request merged**
