### PR TITLE
Ignore poison errors in watch

### PR DESCRIPTION
**Pull request by Darksonn**
Closes: #3445

### CODE REVIEW

**Comment by carllerche** [comment]
Should this be implemented by removing the `Result` from the `RwLock` shim we use? `std` returns `Result` but `parking_lot` does not.

**Comment by Darksonn** [comment]
Apparently poison errors cannot be triggered because `Ref` only contains a read guard.

**Comment by carllerche** [comment]
> Apparently poison errors cannot be triggered because `Ref` only contains a read guard.

@Darksonn is this related to my comment?

**Comment by Darksonn** [comment]
No, it was related to discussion in the linked (now closed) issue.

**Comment by Darksonn** [comment]
Closing as the failure is not possible to trigger. We may potentially still want to add an `RwLock` wrapper that ignores poison errors.

**Pull request closed without merging**
