### PR TITLE
Corrected tinydb example to use tokio mutex instead of std mutex

### PR DESCRIPTION
**Pull request by hashedone**
## Motivation

#2193 
This is not actual bug using std mutex in this particular case, but it is not idiomatic and may show bad practice in general.

## Solution

Change std mutex to tokio mutex in tinydb example

### CODE REVIEW

**Comment by carllerche** [comment]
Could you explain why using a tokio mutex is preferable here?

**Comment by hashedone** [comment]
@carllerche I can agree, that in this particular example locking std mutex is not a problem, but in general it is not idiomatic.

Technically it might be even beneficial in terms of performance (I did some benches and if mutex is just locked and some trivial op is done - like assignment to underlying u32) - on my machine, locking std mutex took ~2.3s, and for tokio mutex took ~5s (obviously for run whole test of like 10M iterations). However if there is some concurrency introduced (same test, but instead of iterating through stream, I used `for_each_concurrent` and spawned a future as task - which is much more real live case in my opinion - if we want do everything sequentially on single task, it should be probably done with blocking IO), then difference is much smaller - something like 10s vs 14s (per whole test). Obviously this is because those additional time is task spawning overhead (or at least this is what I assumed), but it makes the std mutex benefit much less noticable. If an operation performed in handler is more expensive (I tested on assignment), then overhead is probably even less important.

The problem with using std mutex is obvious - even abstracting, that it may suspend whole worker thread for a while (which may or may not be a big issue) it may introduce deadlock (if there is any awaiting while mutex is locked - if this await is not related to locked mutex in any way, it would not introduce deadlock with tokio mutex, but may with std mutex - if other task would try to lock it, it would just wait, not changing task - if it would happen on all workers, we got deadlock).

Also in case where deadlock is actually happening because of invalid logic (so deadlock is introduced on both std mutex and tokio mutex), then tokio mutex would freeze only tasks which are interested with this mutex. Std mutex would freeze whole worker (an possibly whole application).

Now rewinding. This particular code is an example. My feeling is that examples should show idiomatic code. Much more idiomatic would be using tokio mutex. The only case where std mutex should be considered are microoptimizations (which should go in pair in true real live benchmarking of actual code which proves, that the mutex overhead are relevant in particular case). Even in this case, engineers should spend their time to proove, there is no risk about deadlock (for example show, that there is no awaiting while mutex is locked). This is trivial for this case, but it is not something which is obvious for someone who doesn't understand async programming gotchas. Also this may be used in argumentation for using this kind of mutex on production code ("Even tokio does that").

Obviously there is another way to deal with this - change `spawn` on line 118 to `spawn_blocking`, but I find it less educational.

I mentioned my benchmarks - I would probably publish them in near future, but I need time to rethink them, maybe redo, and prepare some more commentary (to explain what I benched and why), so don't expect it too soon.

**Comment by LucioFranco** [comment]
Do we have other examples that use the tokio mutex? If so I think it makes sense to leave this one as an example that does't use our async mutex.

As for the deadlock, you can't actually hold the guard across a yield point since it would then make the future !Send. Therefore you can't really deadlock unless you use localset.

**Comment by hashedone** [comment]
There are examples using tokio mutex. The question is - is using std mutex idiomatic, and if not, do you want to show not idiomatic code in your examples? The point that you cannot cause deadlock by locking over yield point is fair, but you still can block executor without reason easly.

**Comment by LucioFranco** [comment]
I don't think idomatic is the right term here, since in some cases using a std::mutex is idomatic and in other it is not.

But remember blocking _can_ be fine, you need to quantify. The REAL point here is what are you doing with the mutex, if you're just inserting into a hashmap then you are much better off using std mutex.

I agree this could be more clear, I'd rather see tinydb get improved docs on _why_ std::mutex is better here than swapping it out for tokio mutex.

Let me know if that makes sense! :) You have some good points and I think a lot of this just comes down to education and how we explain things. Which of course we could do much much better at.

**Comment by hashedone** [comment]
To be completely honest - I understand your point, and I agree that sometimes it may make sense to use std mutex. But for me it is a little like using linked list in place of vector (maybe a little more common) - it is not less safe, but in general less performant (because it may freeze the executor). Possibly in some cases it may give performance boost, but I really don't see a reason why to go there without good benchmarks.

Possibly I make problem much bigger than it is in reality, so I understand if you prefer to keep it as it is. I learned pretty much anyway while doing my benchmarks recently. The initial problem is that I actually got deadlock in code I was working at, and after hours of working I blamed (now I see that maybe incorrectly) missuse of std mutex in async code, and this example was given to me as "even tokio does it" kind of argument. Then I started digging into it, and was basing mostly on my experiences from C++ mostly (but you convinced me, that actually deadlock I am worried the most is not a case). I would dive into it more anyway.

**Comment by hawkw** [comment]
> But for me it is a little like using linked list in place of vector (maybe a little more common) - it is not less safe, but in general less performant (because it may freeze the executor).

_Is_ it less performant in general? If the performance picture basically depends on whether the length of a critical section is longer than the overhead of a round-trip through the scheduler, my intuition is that a majority of critical sections are short...

**Comment by hashedone** [comment]
@hawkw my intuition is, that in practice it is very hard to maintain critical sections so short, that collisions doensn't occur, but this would require serious benchmarks and I agree that I might be wrong here.

**Comment by Matthias247** [comment]
I think a synchronous Mutex is absolutely the right choice here, and changing it would send out the wrong message. Asynchronous Mutexes are tools that allow to hold exclusive access to a resource across yield points.

For a use-case like the one in the example - which is a non-blocking access to a shared memory data-structure - they will provide absolutely no benefit and decrease performance.

I agree that the async world is hard, since we add a complete new dimension of tools that users need to be aware about - you need to know when to use a synchronous vs. non-blocking Mutex, understand differences in lifetimes, cancellation etc. But blindly advertising to always use async types is not a good option.

> I agree this could be more clear, I'd rather see tinydb get improved docs on why std::mutex is better here than swapping it out for tokio mutex.

I agree on that one. Might be good to add docs that elaborate when to use a synchronous Mutex in the async context. My phrasing would be along:

> We use a synchronous Mutex here, since the code which acquires the Mutex does only update a shared datastructure inside the critical section. This will only take a small number of CPU cycles and will not block - e.g. on IO.

**Comment by carllerche** [comment]
I think @Matthias247 is correct that, in this example, the `std` mutex is correct. Do we have examples that demonstrate when to use an async mutex?

**Pull request closed without merging**
