### PR TITLE
Add example from blog post

### PR DESCRIPTION
**Pull request by Hoverbear**
Adds the example from https://medium.com/@carllerche/announcing-tokio-df6bb4ddb34#.s2jti29o3 to the examples directory.

### CODE REVIEW

**Comment by daschl** [comment]
👍

**Comment by Hoverbear** [comment]
You're quite right this obviously doesn't have a timeout.

**Comment by Hoverbear** [comment]
Updated.

**Comment by carllerche** [comment]
Thanks. Merged: f6584196ddc8e4610a0a2d7d76c3b7fea7b917a1

**Comment by moderation** [comment]
After compiling and running `curl localhost:4000` I get the following error:

`curl: (56) Recv failure: Connection reset by peer`

Is that expected?

**Comment by carllerche** [comment]
Yes, because the socket is closed immediately after it is accepted. The example could be extended to do something more real at some point.

**Pull request closed without merging**
