### PR TITLE
Improve discoverability of Code of Conduct

### PR DESCRIPTION
**Pull request by EverlastingBugstopper**
May want to change the email address - I put in the one I found on @carllerche's Github page 😄

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for this. Do we need to vendor our own copy? In general, the readme states we follow the same code as Rustlang. If we vendor something, it should be the same text? WDYT?

For email: `moderation@tokio.rs` is setup.

**Comment by EverlastingBugstopper** [comment]
Ah - perhaps it's worth creating a `CODE_OF_CONDUCT` that just links to the one in Rustlang. I guess it's not entirely necessary, I'm just used to a `CODE_OF_CONDUCT.md` existing in the repo.

**Comment by carllerche** [comment]
we also have [this](https://github.com/tokio-rs/tokio/blob/master/CONTRIBUTING.md#conduct) note here. It seems fine to duplicate, I don't have much of an opinion, though we should include the email in both places?

**Comment by EverlastingBugstopper** [comment]
Ok! I've updated it there as well 😄

**Comment by carllerche** [comment]
Thanks :+1:

**Pull request merged**
