### PR TITLE
tokio: Add initial time driver metrics

### PR DESCRIPTION
**Pull request by LucioFranco**
This adds the initial time driver metrics.

Ref: https://github.com/tokio-rs/tokio/issues/4073

### CODE REVIEW

**Comment by carllerche** [comment]
@LucioFranco what is left for this?

**Comment by Darksonn** [comment]
What is the status of this?

**Comment by LucioFranco** [comment]
Happy to mentor someone through this work though.

**Comment by carllerche** [comment]
Thanks for the work you have put in so far. I'm going to close this PR as it has gone stale. If someone wishes to resume this work, feel free to open a new PR.

**Pull request closed without merging**
