### PR TITLE
Handle errors properly in examples

### PR DESCRIPTION
**Pull request by liranringel**
Fixes the examples part of #657.

### CODE REVIEW

**Comment by tobz** [comment]
@liranringel Can you rebase/fix the conflicts in this?  Looks good overall, but can't approve/merge until it's all green.

**Comment by carllerche** [comment]
I merged master, let's see what CI says.

**Comment by carllerche** [comment]
It looks like CI is still unhappy.

**Comment by liranringel** [comment]
@carllerche there are real errors.
I ran the tests only on my windows machine. I'll fix it.

**Comment by tobz** [comment]
@liranringel Ah, nice catch on the `tokio-signal` issues!  Not sure how those got on to master... 🤔

**Comment by tobz** [comment]
Ah damn, it looks like that particular tokio-signal tet is broken on 1.26 due to a lack of extern prelude support?  The compiler doesn't give you the implicit extern within the module, so it doesn't know about `std`.

I think you can either rewrite it as `::std::error::Error` or add a separate `use` for `std::error` in `mod platform` to make it pass on 1.26.

**Pull request merged**
