### PR TITLE
Add tokio_fs::read_to_string

### PR DESCRIPTION
**Pull request by sfackler**
`tokio_fs::read` and `tokio_fs::write` already exist - this is the third utility function added to `std::fs` back in 1.26.

### CODE REVIEW

**Comment by sfackler** [comment]
Test failure looks unrelated.

**Comment by carllerche** [comment]
Looks like a racy test. Could you push an empty commit to restart CI? I don't think azure has a button to press.

**Comment by sfackler** [comment]
Retriggered

**Comment by carllerche** [comment]
You are just not having any luck!

**Comment by carllerche** [comment]
spurious networking failure while downloading rust it looks like.

**Comment by taiki-e** [comment]
Retriggered (via "re-run" button)

**Comment by carllerche** [comment]
@taiki-e I feel like I've tried that in the past and it didn't work... good to know, thanks.

**Pull request merged**
