### PR TITLE
sync: add owned semaphore permit

### PR DESCRIPTION
**Pull request by Darksonn**
This implements the suggestion in @hawkw's comment on [#1998][1].

[1]: https://github.com/tokio-rs/tokio/issues/1998#issuecomment-616695722

### CODE REVIEW

**Comment by Darksonn** [comment]
I had used `self: &Arc<Self>`, which requires a too-new Rust version. However apparently we can use `self: Arc<Self>` just fine, so I changed it to that.

**Comment by hawkw** [comment]
Oh, lol, I wrote an almost word-for-word identical version of this a couple days ago but didn't open a PR. LGTM! :+1:

**Comment by hawkw** [comment]
It might also be nice to have a similar API for `Mutex` (and maybe even `RwLock`?) In Linkerd, I ended up [just hacking around this](https://github.com/linkerd/linkerd2-proxy/pull/490/files#diff-4e8bfb222f0eb6d17751512c31194264R54-R60) which isn't that bad, but it could be nice.

**Comment by Darksonn** [comment]
Someone did ask for such an api on `Mutex` a few days ago on discord.

**Pull request merged**
