### PR TITLE
Update Cargo.toml to use local tokio-io

### PR DESCRIPTION
**Pull request by kpp**
Error:

```
error[E0277]: the trait bound `flate2::write::GzEncoder<Count<tokio_io::io::WriteHalf<tokio::net::TcpStream>>>: tokio_io::AsyncWrite` is not satisfied
  --> examples/compress.rs:93:19
   |
93 |     let process = io::copy(read, write).and_then(|(amt, _read, write)| {
   |                   ^^^^^^^^ the trait `tokio_io::AsyncWrite` is not implemented for `flate2::write::GzEncoder<Count<tokio_io::io::WriteHalf<tokio::net::TcpStream>>>`
   |
   = note: required by `tokio_io::io::copy`

error[E0599]: no method named `and_then` found for type `tokio_io::io::Copy<tokio_io::io::ReadHalf<tokio::net::TcpStream>, flate2::write::GzEncoder<Count<tokio_io::io::WriteHalf<tokio::net::TcpStream>>>>` in the current scope
  --> examples/compress.rs:93:41
   |
93 |     let process = io::copy(read, write).and_then(|(amt, _read, write)| {
   |                                         ^^^^^^^^
   |
   = note: the method `and_then` exists but the following trait bounds were not satisfied:
           `tokio_io::io::Copy<tokio_io::io::ReadHalf<tokio::net::TcpStream>, flate2::write::GzEncoder<Count<tokio_io::io::WriteHalf<tokio::net::TcpStream>>>> : futures::Future`
           `&mut tokio_io::io::Copy<tokio_io::io::ReadHalf<tokio::net::TcpStream>, flate2::write::GzEncoder<Count<tokio_io::io::WriteHalf<tokio::net::TcpStream>>>> : futures::Future`
           `&mut tokio_io::io::Copy<tokio_io::io::ReadHalf<tokio::net::TcpStream>, flate2::write::GzEncoder<Count<tokio_io::io::WriteHalf<tokio::net::TcpStream>>>> : futures::Stream`

error: aborting due to 2 previous errors

error: Could not compile `tokio`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Why is it a problem? Seems like the trait should have been implemented for GzEncoder https://github.com/alexcrichton/flate2-rs/blob/master/src/gz/write.rs#L160

### CODE REVIEW

**Comment by carllerche** [comment]
Two different versions of tokio-io are being pulled in. I'm not 100% sure why.

**Comment by kpp** [comment]
I fixed it locally  by:

tokio/Cargo.toml:
```diff
diff --git a/Cargo.toml b/Cargo.toml
index 9ab71e3..8d3d82f 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -45,7 +45,7 @@ futures = "0.1.16"
 
 [dev-dependencies]
 env_logger = { version = "0.4", default-features = false }
-flate2 = { version = "1", features = ["tokio"] }
+flate2 = { version = "1", features = ["tokio"], path = "/home/humbug/flate2-rs" }
 futures-cpupool = "0.1"
 http = "0.1"
 httparse = "1.0"
```

flate2-rs/Cargo.toml:
```diff
diff --git a/Cargo.toml b/Cargo.toml
index 3d89a93..2c49609 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -22,7 +22,7 @@ streams.
 libc = "0.2"
 miniz-sys = { path = "miniz-sys", version = "0.1.7", optional = true }
 libz-sys = { version = "1.0", optional = true }
-tokio-io = { version = "0.1", optional = true }
+tokio-io = { version = "0.1", optional = true, path = "/home/humbug/tokio/tokio-io" }
 futures = { version = "0.1", optional = true }
 miniz_oxide_c_api = { version = "0.1", optional = true, features = ["no_c_export"]}
```

> Two different versions of tokio-io are being pulled in.

You are correct.

The problem is that once there is a new crate that uses `tokio-executor` or `tokio-threadpool` and that is included inside `tokio` (as `flate2-rs` was included), `tokio` build will be broken.

**Comment by carllerche** [comment]
Closed by #166

Thanks for the work 👍

**Comment by kpp** [comment]
> The problem is that once there is a new crate that uses tokio-executor or tokio-threadpool and that is included inside tokio (as flate2-rs was included), tokio build will be broken.

Ok, you patched crates, but the same issue may occur with tokio-executor or tokio-threadpool in the future.

**Comment by carllerche** [comment]
It might... the same trick should be used in that case.

**Pull request closed without merging**
