### PR TITLE
Re-export tokio-fs

### PR DESCRIPTION
**Pull request by 95th**

### CODE REVIEW

**Comment by archseer** [comment]
Needs re-enabling here too: https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml#L30

**Comment by 95th** [comment]
> Needs re-enabling here too: https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml#L30

It is already enabled. I have rebased the PR just to make sure.

**Comment by 95th** [comment]
CI failed with following network error:

```
error: failed to download from `https://crates.io/api/v1/crates/bytes/0.4.12/download`

Caused by:
  [35] SSL connect error (schannel: failed to receive handshake, SSL/TLS connection failed)
```

**Comment by archseer** [comment]
Ah sorry, I misread the commit on my mobile! Looks fine 👍

**Comment by 95th** [comment]
@LucioFranco Is there a problem with merging this one?

**Comment by LucioFranco** [comment]
Nope just lost track :)

**Pull request merged**
