### PR TITLE
style: use rust instead of c

### PR DESCRIPTION
**Pull request by wathenjiang**
style: use rust instead of c

### CODE REVIEW

**Comment by wathenjiang** [comment]
The value of bool, true is 1, false is 0. It is a little bit tricky in Rust, which is C style.

**Comment by Darksonn** [comment]
I think this is fine as it is. The `map_or` is also a bit awkward with the closure.

**Comment by wathenjiang** [comment]
the bool to usize is a implicit map op too, but in the way of `as`.

**Comment by wathenjiang** [comment]
The https://github.com/rust-lang/rust/blob/7cc3da05f99fbc89782fc6cb7e207fa11aa6add5/src/tools/rust-analyzer/crates/hir-ty/src/lower.rs#L1108 is almost the same way, but such scenario is really rare in rust.

**Comment by taiki-e** [comment]
Converting a bool to an integer using cast or from/into is common enough in Rust. Clippy also has a lint that suggests it instead of if-else.

https://rust-lang.github.io/rust-clippy/master/index.html#/bool_to_int_with_if

**Comment by wathenjiang** [comment]
> Converting a bool to an integer using cast or from/into is common enough in Rust. Clippy also has a lint that suggests it instead of if-else.

Thanks.

**Pull request closed without merging**
