### PR TITLE
tokio-threadpool: bump crossbeam-deque to 0.4

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by carllerche** [comment]
Unfortunately, the latest crossbeam does not support the versions of Rust that Tokio targets. I believe it requires 1.25? If so, we need to wait a bit before merging this.

**Comment by kpp** [comment]
crossbeam-utils is now 0.4.1 with a patch for `cargo doc` on nightly.

**Comment by kpp** [comment]
Depends on #465

**Comment by dekellum** [comment]
The latest version of crossbeam-deque is 0.5.1 as of this note.  Assuming that version works as well, why shouldn't the tokio-threadpool dependency be expressed more broadly as ">= 0.3.1, < 0.6" or something similar? This way tokio continues to be usable on older rust using an older crossbeam. 

Or should it remain expressed this way (e.g. 0.4 == "^0.4" ==  ">= 0.4.0, < 0.5") just because cargo doesn't yet have the information and support reasoning about the rustc minimum versions?

cc: @stjepang

**Comment by dekellum** [comment]
Oh, and then there is #468. :) Could a a more broadly expressed dependency range satisfy all of these while still offering backward support for older rust versions?

**Comment by dekellum** [comment]
The merge of #465 might be reconsidered before release, as it might be unnecessary or unwarranted?  I'm asking with this, so please correct me if I'm wrong. Also I'm referring to dependency strategy which might sooner allow use of 0.5.1, with the perhaps optimistic idea that its compatible. #468 makes other changes beyond a mandator upgrade to "0.5.0" meaning ">= 0.5.0, < 0.6", so I'm not entirely sure, but I suspect @stjepang knows the answer!

**Comment by carllerche** [comment]
As far as I know, cargo (dependency resolver) does not work that well with more complex dependency ranges, so I would rather stick with simpler dependency requirements.

**Comment by dekellum** [comment]
OK, fair enough, thanks.

**Comment by tobz** [comment]
@dekellum I think we can revisit this? With #465 landed, this most likely needs a rebase and a re-run of the CI.

/cc @carllerche

**Comment by dekellum** [comment]
@tobz I don't follow. What action are you suggesting?  I have my own opinions (per prior comments here and remaining) on the potential safety of broadening dependency ranges, for tokio or otherwise, but this is likely not the place to further discuss that?

**Comment by tobz** [comment]
My comment is orthogonal from dependency ranges.

#465 bumped up Tokio to supporting Rust 1.25 at a minimum, which was, AFAICT, the original issue blocking this PR.

With #465 merged, that shouldn't be an issue anymore.

**Comment by dekellum** [comment]
Unless I'm missing something important, this PR should be closed, because #468 has been merged since, updating `tokio-threadpool` to `crossbeam-deque` to (^)0.5.0.  Note however that tokio-threadpool has yet to be *released* with that upgrade.

**Comment by tobz** [comment]
Ah, right you are!  I gotta pay more attention, heh.

Yeah, I think you can close this.  I opened #520 to get a new release cut for `tokio-threadpool`.

**Pull request closed without merging**
