### PR TITLE
Add `SinkWriter` in analogy to `StreamReader` to `tokio_util`

### PR DESCRIPTION
**Pull request by dbischof90**
## Motivation
Tokio provides `StreamReader`, enabling us to treat streams as file-like interfaces through `AsyncRead`. This however only exists for streams, not for general sinks, for which this PR provides an implementation.

## Solution
The solution is a wrapper which acts as a buffer that sends and flushes provided bytes into the sink. Should a fully successful sending operation not be possible, the buffer is added to an internal buffer which is handled with a higher priority once another sending operation is attempted again.
A vectorized write is not provided - this operation flushes only at the end and the default implementation is about as effective as a generic sink can be I believe.

There are two points to discuss: in case the `start_send` operation fails, the polling method returns `Ok` with the number of bytes sent since part of the operation was indeed successful. As such an error would most likely come from a close, another attempt to send data would then lead to an error. This is a compromise of being able to return the number of bytes sent and forwarding the error in a low-friction way. A second item would be the question whether this solution is not "too eager" in waking up the context, which I'm not sure about.

### CODE REVIEW

**Comment by Darksonn** [comment]
This seems way more complicated than it needs to be. If we require the sink to have item type `&[u8]`, then the `poll_write` call could just do `poll_ready` and pass the buffer to `start_send` if we get `Ready`.

**Comment by dbischof90** [comment]
The trait bound wasn't adding a lot of complexity so I thought why not. 


What is more of a headache IMO and where I spent a bit more time is what to do if there is a (temporary) disconnect in the middle, you have a few failed sensing attempts and you keep on "stuffing down bytes" into the sink. Think about writes to a bounded queue which doesn't receive properly for whatever reason. I wouldn't say it's fine for the implementation to send some buffer twice (you start sending the first buffer, it fails after half the package, you retry and send again).


On that way, the user doesn't have to care about resending buffers and clean up partial duplicates on the receiving end. Or am I misunderstanding what you mean?

**Comment by Darksonn** [comment]
Writing bytes individually is definitely not what we want. That's incredibly inefficient.

**Comment by Darksonn** [comment]
We discussed various ways to improve this on discord, but it doesn't seem like they have been applied yet. For now, I will close this due to inactivity. However, if you make further progress on this PR, then you are very welcome to re-open the PR with your updates.

**Pull request closed without merging**
