### PR TITLE
udp: Prep release v0.1.5

### PR DESCRIPTION
**Pull request by LucioFranco**
This is blocked on #1517 being merged first.

### CODE REVIEW

**Comment by carllerche** [comment]
Should be good to rebase & merge.

**Comment by LucioFranco** [comment]
Before we merge this @kpp can you let us know that this will fix your issues introduced in 0.1.4?

**Comment by kpp** [comment]
> can you let us know

Yes I will test it.

Also I added more unit tests to catch bugs like this in the future

**Comment by LucioFranco** [comment]
@kpp awesome, once you give me the +1 I will publish this change.

And sorry for the change! Totally my fault, technically speaking, this wasn't a breaking change since it follows the `Decoder::decode` contract but I should have been more careful. Thanks for originally opening the issue <3

**Comment by kpp** [comment]
```
~/tokio$ git log -n1
commit 9339ebb0caa4e2b978d63508cceea5d896f73c54 (HEAD -> udp_framed, kpp/udp_framed)
Author: Roman Proskuryakov <humbug@deeptown.org>
Date:   Sat Aug 31 00:32:48 2019 +0300

    Add more unit tests for UdpFramed
```


```diff
~/tox$ git diff
diff --git a/Cargo.toml b/Cargo.toml
index 1801a30..a3b14ae 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -41,10 +41,11 @@ parking_lot = "0.8"
 failure = "0.1"
 lru = "0.1"
 bitflags = "1.0"
-tokio-udp = "=0.1.3"
+#tokio-udp = "=0.1.3"
 
 [dependencies.tokio]
 version = "0.1"
+path = "../tokio/tokio"
 default-features = false
 features = ["tcp", "udp", "timer", "codec", "rt-full"]
```

```
~/tox$ cargo test && echo "+1"
...
+1
```

Confirmed =)

**Comment by LucioFranco** [comment]
@kpp awesome, will publish this in the next 5min!

**Comment by kpp** [comment]
Wait... how about tests? https://github.com/tokio-rs/tokio/pull/1522 ...

**Comment by LucioFranco** [comment]
@kpp good catch I totally missed that! One sec.

**Pull request merged**
