### PR TITLE
Add `fs::try_exists`

### PR DESCRIPTION
**Pull request by kevinkassimo**
## Motivation

`std` has added `Path::exists` and (unstable) `fs::try_exists`. Adding `try_exists` to `tokio::fs` based on prior discussions in #3375 (which has not been updated for a while)

## Solution

Add `fs::try_exists` function.
Fixes: #3373

### CODE REVIEW

**Comment by Darksonn** [comment]
Let's wait for std to stabilize `try_exists`. I'd rather not stabilize this, then see std change the signature of theirs so we don't match.

**Comment by isikkema** [comment]
`try_exists` has now been stabilized in std https://github.com/rust-lang/rust/pull/97912.
Perhaps this should be revisited?

**Comment by Darksonn** [comment]
Sure! I see that it hasn't been released yet, but I would be happy to include our own version of it when that happens.

**Comment by just-chillin** [comment]
Unless I'm misunderstanding looks like `std::path::try_exists` has been stabilized? https://github.com/rust-lang/rust/pull/97912

Would you folks find it helpful if I contributed a version using `Path::try_exists`?

**Comment by Darksonn** [comment]
Well, the documentation for [`fs::try_exists`](https://doc.rust-lang.org/stable/std/fs/fn.try_exists.html) still says "This is a nightly-only experimental API". Once that changes, I would be happy with adding it to Tokio.

**Comment by Darksonn** [comment]
Ah, I see. It's been stabilized as `Path::try_exists`. That's an interesting situation because we don't have a `Path` type in Tokio. In that case, I am ok with adding an `tokio::fs::try_exists` as a replacement, since we cannot mirror what std is doing.

**Comment by kevinkassimo** [comment]
It seems that minrust is installing Rust 1.49.0 which is too hold for the feature? (at 1.63.0) Can I update it in the ci.yml file?

**Comment by brodybits** [comment]
As an outside contributor, I would personally consider that to be a breaking change and vote for something that will work with Rust 1.49, if possible. From a quick search I found this: https://stackoverflow.com/questions/32384594/how-to-check-whether-a-path-exists

But some may not agree with me.

See https://doc.rust-lang.org/cargo/reference/semver.html#env-new-rust

**Comment by Darksonn** [comment]
Ah, yes, we need to use an implementation that will work on 1.49. Sorry if that was unclear. My main concern was matching the API in std, but it turns out that they have chosen an API we cannot match, so I am ok with moving forward with an `fs::try_exists` instead.

**Comment by kevinkassimo** [comment]
Updated implementation to use the exact [fs::try_exists impl from std](https://github.com/rust-lang/rust/blob/5243ea5c29b136137c36bd773e5baa663790e097/library/std/src/sys_common/fs.rs#L45-L51)

**Comment by brodybits** [comment]
> Updated implementation to use the exact [fs::try_exists impl from std](https://github.com/rust-lang/rust/blob/5243ea5c29b136137c36bd773e5baa663790e097/library/std/src/sys_common/fs.rs#L45-L51)

Another outsider comment I would kinda favor adding a comment with this info.

**Comment by just-chillin** [comment]
Looks great! Thanks so much!

**Review by Darksonn — APPROVED** [review]
Thanks.

**Comment by just-chillin** [comment]
🙌🏻

**Pull request merged**
