### PR TITLE
chore: remove `tokio-trace`, add "Related Projects" to README

### LINKED ISSUE #1159: trace: Move to separate repository
`tokio-trace` is not tightly coupled to `tokio`, in particular, it does not depend on any of the other `tokio` crates. Having `tokio-trace` in the same repository as `tokio` can slow down development of both `tokio-trace` and the other `tokio` crates, as unrelated changes can cause CI build failures, branches can require complex rebases and merges, and it's necessary to build and test all of `tokio` on changes that only touch `trace`. Furthermore, it reinforces the misconception that it's _necessary_ to be using `tokio` to use `tokio-trace`. Finally, it would be nice to have separate issue trackers for `tokio` and `tokio-trace`.

I propose moving `tokio-trace` and `tokio-trace-core` to a new `tokio-rs/trace` repository. I think it would be valuable to preserve the git history for tokio-trace, so we should use `git  filter-branch` to split out the trace commits from this repository.

Some necessary tasks:

- [x] wait for all currently in-flight `tokio-trace` PRs to merge
- [x] use `git filter-branch` to extract the `tokio-trace` commits from this repo's git history
- [x] push filtered repo to `tokio-rs/tokio`
- [x] move tokio-trace issues to new repository
- [x] set up CI builds for `tokio-rs/tokio`
- [x] update links in documentation
- [x] consider creating a new `tokio-rs/trace` gitter channel?

It might be worthwhile to do this _before_ cutting the next trace release, so that the repo links in the crate metadata on docs.rs and crates.io can point to the new repository.

### PR DESCRIPTION
**Pull request by hawkw**
## Motivation

The `tokio-trace` and `tokio-trace-core` crates have been renamed to
`tracing` and `tracing-core`, and moved to their own repository
(`tokio-rs/tracing`).

## Solution

This branch removes `tokio-trace` and `tokio-trace-core` from the
`tokio` repository. In addition, I've added a "Related Projects" section
to the root README, which lists `tracing` (as well as  `mio`, and
`bytes`) as other libraries maintained by the Tokio project. I thought
that this would help folks looking for `tokio-trace` here find it in its
new home.

Closes #1159

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### CODE REVIEW

**Comment by jonhoo** [comment]
Along with this change, `tokio` also needs to be updated to use `tracing-core` instead of `tokio-trace-core`:
```diff
diff --git a/tokio/Cargo.toml b/tokio/Cargo.toml
index 83b5f6a0..7b76bd1b 100644
--- a/tokio/Cargo.toml
+++ b/tokio/Cargo.toml
@@ -47,7 +47,7 @@ rt-full = [
   "tokio-current-thread",
   "tokio-executor",
   "tokio-threadpool",
-  "tokio-trace-core",
+  "tracing-core",
 ]
 sync = ["tokio-sync"]
 tcp = ["tokio-tcp"]
@@ -73,7 +73,7 @@ tokio-threadpool = { version = "0.1.14", optional = true }
 tokio-tcp = { version = "0.1.0", optional = true }
 tokio-udp = { version = "0.1.0", optional = true }
 tokio-timer = { version = "0.2.8", optional = true }
-tokio-trace-core = { version = "0.2", optional = true }
+tracing-core = { version = "0.1", optional = true }

 # Needed until `reactor` is removed from `tokio`.
 mio = { version = "0.6.14", optional = true }
diff --git a/tokio/src/lib.rs b/tokio/src/lib.rs
index 19766090..ba1791f9 100644
--- a/tokio/src/lib.rs
+++ b/tokio/src/lib.rs
@@ -128,7 +128,7 @@ pub mod util;

 if_runtime! {
     extern crate tokio_executor;
-    extern crate tokio_trace_core;
+    extern crate tracing_core;
     pub mod executor;
     pub mod runtime;

diff --git a/tokio/src/runtime/threadpool/builder.rs b/tokio/src/runtime/threadpool/builder.rs
index 030b3ca2..55b41865 100644
--- a/tokio/src/runtime/threadpool/builder.rs
+++ b/tokio/src/runtime/threadpool/builder.rs
@@ -12,7 +12,7 @@ use tokio_reactor;
 use tokio_threadpool::Builder as ThreadPoolBuilder;
 use tokio_timer::clock::{self, Clock};
 use tokio_timer::timer::{self, Timer};
-use tokio_trace_core as trace;
+use tracing_core as trace;

 /// Builds Tokio Runtime with custom configuration values.
 ///
```

Note that this whole change should also be applied to the `v0.1.x` branch.

**Comment by hawkw** [comment]
@jonhoo thanks for catching that! i'll backport the change to `v0.1.x` as well, but i think the diff is _slightly_ different due to `extern crate`.

**Comment by carllerche** [comment]
I would only worry about 0.1.x if you think it is critical.

**Comment by jonhoo** [comment]
@carllerche it is critical in the sense that otherwise `tracing::dispatcher::with_default` when creating a `tokio::Runtime` won't work.

**Comment by carllerche** [comment]
@jonhoo up to you, personally I am ok w/ it, but if it blocks anyone, then we can update

**Pull request merged**
