### PR TITLE
rename tokio-tls to tokio-native-tls

### PR DESCRIPTION
**Pull request by djc**
## Motivation

Rename tokio-tls to tokio-native-tls to make it clearer what the underlying implementation is. This would also allow to put it on more equal footing with tokio-rustls, which we could potentially pull in-tree after this. See #1268, which is listed as part of the 0.2 blockers.

## Solution

So far, I simply renamed tokio-tls to tokio-native-tls. The transition to 0.2 seems like a decent opportunity to make this breaking change.

cc @sfackler

### CODE REVIEW

**Comment by LucioFranco** [comment]
I think this makes sense!

**Comment by DoumanAsh** [comment]
I don't think it makes much sense, we already have the crate with `tokio-tls` why to duplicate the same crate but with different name?
Even if it reflects current nature of it, it is not necessary that we always stick with native-tls

**Comment by djc** [comment]
It doesn't duplicate the crate, it gives it a different name. The point is that tokio-native-tls is a particular implementation of the TLS protocol, that multiple implementations are protocol and that there are real trade-offs between these implementations such that it is difficult to be opinionated about this. The name "tokio-tls" itself invokes the idea of an official or singularly supported implementation, whereas some of the other implementations might be equally viable.

**Comment by DoumanAsh** [comment]
`tokio-tls` is TLS implementation provided by tokio
You do not need to consider anything else.

If user actually care about underlying implementation, he'll take a look at source code(Cargo manifest is more than enough)

>It doesn't duplicate the crate, it gives it a different name

The point is it produces extra crate for no reason

Well, I don't really care if others are fine with it

**Comment by sfackler** [comment]
@DoumanAsh tokio-tls is explicitly a wrapper around native-tls - that's exposed through it's public API.

**Comment by LucioFranco** [comment]
I'd eventually like to see `tokio-openssl`, `tokio-rustls` and `native-tls` support folded into one crate possibly via feature flags.

**Comment by djc** [comment]
That sounds like https://github.com/stepancheg/rust-tls-api/.

**Comment by carllerche** [comment]
Going the `rust-tls-api` route is probably an option.

We could do something like update the crate to, by default, only provide the API and have each implementation be a feature flag. Then libs that require TLS only depend on `tokio-tls` and end users can depend on `tokio-tls` w/ the tls library they want.

We could also conditionally include APIs for ALPN as well.

**Comment by carllerche** [comment]
Thanks for getting this discussion started :+1:

As mentioned above, I think we should explore making `tokio-tls` a facade crate itself and support rustls & native-tls via feature flags.

**Pull request closed without merging**
