### PR TITLE
Enable ASAN tests in CI

### PR DESCRIPTION
**Pull request by Finomnis**
Related to https://github.com/tokio-rs/tokio/issues/4639.

## Motivation

There seem to be multiple memory leaks in unsafe parts of tokio.

Specifically, I found one in tokio_util::sync::CancellationToken and wrote a failing test for it.
Further, I added llvm's ASAN to the CI as it seems to find more leaks than valgrind.
It shouldn't break any working code, as [quoted by google](https://clang.llvm.org/docs/AddressSanitizer.html#usage):
> AddressSanitizer does not produce false alarms.

## Solution

- [x] Add llvm-asan to CI
- [x] Add failing grandchild test to CancellationToken test suite
- [ ] Fix memory leak

### CODE REVIEW

**Comment by Darksonn** [comment]
You say multiple. Are you aware of others than the one in `CancellationToken`?

**Comment by Finomnis** [comment]
> You say multiple. Are you aware of others than the one in `CancellationToken`?

I'm aware of another race condition, that I didn't report yet:
- Situation: you have a parent and a child token in two different threads
- Parent `cancel()` ->  `parent.unregister_child()`. Thread pauses at first line
- child thread drops all tokens; `parent.unregister_child()` gets called, runs through, child gets deleted
- Parent thread continues to unregister child from first point. This will result in a memory violation or even a double free

**Comment by Finomnis** [comment]
> You say multiple. Are you aware of others than the one in `CancellationToken`?

Ah and I seem to have gotten more errors than just in `CancellationToken` when I ran asan on the entire codebase:
```text
=================================================================
==26683==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x55688d119fc8 in calloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:77:3
    #1 0x55688d64708b in alloc::alloc::alloc_zeroed::h9897ccaa1bc24d76 /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/alloc/src/alloc.rs:160:14
    #2 0x55688d6478b2 in alloc::alloc::Global::alloc_impl::h6a286aea75d18364 /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/alloc/src/alloc.rs:171:43
    #3 0x55688d649053 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate_zeroed::h732b411d30b5b4c1 /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/alloc/src/alloc.rs:236:9
    #4 0x55688d643a4d in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::h94abbbabb1294cfb /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/alloc/src/raw_vec.rs:187:38
    #5 0x55688d2a422c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_zeroed_in::hd6cb5e0b06eb1298 /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/alloc/src/raw_vec.rs:140:9
    #6 0x55688d2004df in alloc::vec::from_elem::hbedb48850ab73c64 /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/alloc/src/vec/mod.rs:2421:5
    #7 0x55688d149e12 in _$LT$$RF$mut$u20$T$u20$as$u20$tokio..io..async_read..AsyncRead$GT$::poll_read::h981130a163614794 /home/martin/work/tokio/tokio/src/io/async_read.rs:67:13
    #8 0x55688d1467d9 in _$LT$tokio..io..util..read_buf..ReadBuf$LT$R$C$B$GT$$u20$as$u20$core..future..future..Future$GT$::poll::hb19034c5626ded18 /home/martin/work/tokio/tokio/src/io/util/read_buf.rs:57:20
    #9 0x55688d14c96c in io_read::read_buf_bad_async_read::_$u7b$$u7b$closure$u7d$$u7d$::ha63a29589ab50460 /home/martin/work/tokio/tokio/tests/io_read.rs:58:36
    #10 0x55688d16822e in _$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::he3f6bb9da920168e /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/core/src/future/mod.rs:91:19
    #11 0x55688d1432cb in _$LT$core..pin..Pin$LT$P$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h553cf759a6f7cd92 /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/core/src/future/future.rs:124:9
    #12 0x55688d15d8ab in tokio::runtime::basic_scheduler::CoreGuard::block_on::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf22c843b1e700154 /home/martin/work/tokio/tokio/src/runtime/basic_scheduler.rs:507:48
    #13 0x55688d16660d in tokio::coop::with_budget::_$u7b$$u7b$closure$u7d$$u7d$::hbb621d83bc977c54 /home/martin/work/tokio/tokio/src/coop.rs:102:9
    #14 0x55688d16be6e in std::thread::local::LocalKey$LT$T$GT$::try_with::ha80cdeae04b19363 /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/std/src/thread/local.rs:443:16
    #15 0x55688d1691c1 in std::thread::local::LocalKey$LT$T$GT$::with::h62776df399133344 /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/std/src/thread/local.rs:419:9
    #16 0x55688d15d2e4 in tokio::coop::with_budget::hf8d2ccc3e3c8c578 /home/martin/work/tokio/tokio/src/coop.rs:95:5
    #17 0x55688d15d2e4 in tokio::coop::budget::h740531b153f1657b /home/martin/work/tokio/tokio/src/coop.rs:72:5
    #18 0x55688d15d2e4 in tokio::runtime::basic_scheduler::CoreGuard::block_on::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc9468587418b4649 /home/martin/work/tokio/tokio/src/runtime/basic_scheduler.rs:507:25
    #19 0x55688d153640 in tokio::runtime::basic_scheduler::Context::enter::hb8805d501a9ef07b /home/martin/work/tokio/tokio/src/runtime/basic_scheduler.rs:361:19
    #20 0x55688d15afb5 in tokio::runtime::basic_scheduler::CoreGuard::block_on::_$u7b$$u7b$closure$u7d$$u7d$::hf932ac57ce1ec7f3 /home/martin/work/tokio/tokio/src/runtime/basic_scheduler.rs:506:36
    #21 0x55688d1587f4 in tokio::runtime::basic_scheduler::CoreGuard::enter::_$u7b$$u7b$closure$u7d$$u7d$::h9d8849174a9ac6bb /home/martin/work/tokio/tokio/src/runtime/basic_scheduler.rs:564:57
    #22 0x55688d14f68d in tokio::macros::scoped_tls::ScopedKey$LT$T$GT$::set::hcb15a489e41a377b /home/martin/work/tokio/tokio/src/macros/scoped_tls.rs:61:9
    #23 0x55688d157136 in tokio::runtime::basic_scheduler::CoreGuard::enter::ha8958ea4f8c8e171 /home/martin/work/tokio/tokio/src/runtime/basic_scheduler.rs:564:27
    #24 0x55688d158d5f in tokio::runtime::basic_scheduler::CoreGuard::block_on::h9ba3532091e2aa94 /home/martin/work/tokio/tokio/src/runtime/basic_scheduler.rs:497:9
    #25 0x55688d150fe7 in tokio::runtime::basic_scheduler::BasicScheduler::block_on::hd84804bdfc08e3da /home/martin/work/tokio/tokio/src/runtime/basic_scheduler.rs:173:24
    #26 0x55688d1471ec in tokio::runtime::Runtime::block_on::h3fe00167f453ae4a /home/martin/work/tokio/tokio/src/runtime/mod.rs:475:46
    #27 0x55688d144a7a in io_read::read_buf_bad_async_read::hc3ad69b22f43978a /home/martin/work/tokio/tokio/tests/io_read.rs:58:5
    #28 0x55688d14c039 in io_read::read_buf_bad_async_read::_$u7b$$u7b$closure$u7d$$u7d$::h264e082708adc48c /home/martin/work/tokio/tokio/tests/io_read.rs:56:7
    #29 0x55688d1a6202 in core::ops::function::FnOnce::call_once::h7c1c5c3100c766b3 /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/core/src/ops/function.rs:248:5
    #30 0x55688d1a6202 in test::__rust_begin_short_backtrace::hcac4e16a597a6280 /rustc/de1026a67b0a3f5d6b61a1f77093af97d4799376/library/test/src/lib.rs:573:5

SUMMARY: AddressSanitizer: 10 byte(s) leaked in 1 allocation(s).
```

**Comment by Finomnis** [comment]
@Darksonn It seems that the `san` step in the CI does not run tests of nested projects. I wonder if ANY tests of nested projects get run.

**Comment by Darksonn** [comment]
Regarding other `CancellationToken` errors, I am probably going to rewrite the entire `CancellationToken` to be much less unsafe. This isn't the first time we have found bad bugs in it. As for that test you posted, it is the test itself that is deliberately leaking memory as part of the test, and not a leak in Tokio.

**Comment by Finomnis** [comment]
> Regarding other `CancellationToken` errors, I am probably going to rewrite the entire `CancellationToken` to be much less unsafe. This isn't the first time we have found bad bugs in it. As for that test you posted, it is the test itself that is deliberately leaking memory as part of the test, and not a leak in Tokio.

I actually started doing that and had some good ideas. I case you want to sync up.

**Comment by Darksonn** [comment]
If you have ideas for rewriting it, we can chat about it on discord.

**Comment by Finomnis** [comment]
Closed for now. Need to do more experimentation with ASAN in CI on my local branch before re-opening this PR.

**Pull request closed without merging**
