### PR TITLE
signal: migrate to std::futures

### LINKED ISSUE #1193: signal: update to std::future
`tokio-signal` should be updated to use `std::future`.

This issue is to track discussion and progress.

cc @ipetkov

### PR DESCRIPTION
**Pull request by ipetkov**
Migrate to std::futures and the futures 0.3 preview and use async/await
where possible

**Breaking change:** the IoFuture and IoStream definitions used to refer
to Box<dyn Future> and Box<dyn Stream>, but now they are defined as
Pin<...> versions which are technically breaking.

No other breaking or functional changes have been made. Other cleanup which requires breaking changes will come in future PRs

Note: tests are failing due to lack of support for timers in `tokio` at the moment. If this won't get fixed soon we can disable the timeouts in the tests for now...

Fixes #1193

### CODE REVIEW

**Comment by carllerche** [comment]
Super awesome :+1:

Looks like CI doesn't pass. The error is timer related. I plan on bringing back timers to the runtime once #1219 lands.

**Comment by ipetkov** [comment]
@carllerche great, I'll rebase when those changes land

**Comment by qm3ster** [comment]
@ipetkov I think it happened :weary: :ok_hand:

**Comment by ipetkov** [comment]
I've rebased this branch, though the windows tests are timing out, probably due to the issue that #1238 is trying to fix

**Comment by carllerche** [comment]
I am going to track follow up thoughts here #1243. Feel free to add whatever additional thoughts you have.

**Pull request merged**
