### PR TITLE
chore: prepare v0.3.2 release

### PR DESCRIPTION
**Pull request by carllerche**

### CODE REVIEW

**Review by LucioFranco — APPROVED** [review]

**Comment by Darksonn** [comment]
You need to merge #3055 first

**Comment by Darksonn** [comment]
And you're missing the changelog line for that PR (and the tokio-util PR it is a followup to)

**Comment by carllerche** [comment]
The tokio-util change was reverted to avoid changes to `tokio`. This should be good to go now?

**Review by Darksonn — APPROVED** [review]
Looks good.

**Pull request merged**
