### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
I starting review the tokio crates and in doing make a bunch of cleanups commits. Some hightlights:

- Remove unused code.
- Replace `try!` with `?`.
- Prefer to use `Err(io::ErrorKind::WouldBlock.into())`. 
- Ran rustfmt.
- Various cleanups to improve clarity of the code flow.
- Expanded the documentation of about every struct.
- Expanded the module level documentation on every struct and how they link together.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
I also made a number of notes about some possible improvement that would break the API. Should a create an issue for each of them (about 6 or so) or 1 big issue?

**Comment by carllerche** [comment]
Hi, thanks for the PR!

This seems to be conflating a bunch of things into a one PR.  It makes it hard to tell exactly what is going on. It would probably be easier to approach this into more granular PRs. Each PR should make a logical change. This makes it easier to tell how the various changes relate.

Also, please do not run `rustfmt`. I would rather not take any reformatting changes until `rustfmt` is stable.

**Comment by Thomasdezeeuw** [comment]
Ok will do, might take some time.

**Comment by Thomasdezeeuw** [comment]
I've create 5 pull requests instead.

**Pull request closed without merging**
