### PR TITLE
Specify dependencies for tokio-util tests

### PR DESCRIPTION
**Pull request by kaimast**
## Motivation
I noticed that the integration tests for `tokio-util` won't compile unless the `full` feature is specified. 

## Solution
This pull request fixes this problem by specifying feature requirements for all integration tests in `tokio-util/Cargo.toml`.

### CODE REVIEW

**Comment by Darksonn** [comment]
Huh, I did not know that this was possible. If we don't pass the `--features` flag, will it just not run the test, or will it fail?

**Comment by kaimast** [comment]
> Huh, I did not know that this was possible. If we don't pass the `--features` flag, will it just not run the test, or will it run it with the feature enabled.

If you just run `cargo test` it will indeed skip the tests:

```
~/dev/tokio/tokio-util tokio-util-test ?4 ❯ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.13s
     Running unittests (/home/kai/dev/tokio/target/debug/deps/tokio_util-9d8f76d6f8a33cd4)

running 2 tests
test either::tests::either_is_stream ... ok
test either::tests::either_is_async_read ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/context.rs (/home/kai/dev/tokio/target/debug/deps/context-4f0b65b23d724084)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/mpsc.rs (/home/kai/dev/tokio/target/debug/deps/mpsc-02040d7f33b45cc4)

running 4 tests
test close_sender_last ... ok
test test_simple ... ok
test test_abort ... ok
test close_sender_not_last ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/poll_semaphore.rs (/home/kai/dev/tokio/target/debug/deps/poll_semaphore-141b35492eeef089)

running 1 test
test it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/reusable_box.rs (/home/kai/dev/tokio/target/debug/deps/reusable_box-cd0739d6e19c1e73)

running 3 tests
test test_different_futures ... ok
test test_different_sizes ... ok
test test_zero_sized ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/sync_cancellation_token.rs (/home/kai/dev/tokio/target/debug/deps/sync_cancellation_token-b9678dd078777c64)

running 6 tests
test cancel_child_token_through_parent ... ok
test cancel_child_token_without_parent ... ok
test cancel_token ... ok
test create_child_token_after_parent_was_cancelled ... ok
test drop_parent_before_child_tokens ... ok
test drop_multiple_child_tokens ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/time_delay_queue.rs (/home/kai/dev/tokio/target/debug/deps/time_delay_queue-fb1f728647a58e72)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests tokio-util

running 4 tests
test src/sync/cancellation_token.rs - sync::cancellation_token::CancellationToken (line 24) ... ignored
test src/sync/cancellation_token.rs - sync::cancellation_token::CancellationToken::child_token (line 172) ... ignored
test src/either.rs - either::Either (line 20) ... ok
test src/either.rs - either::Either (line 40) ... ok

test result: ok. 2 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out; finished in 0.82s

```

**Comment by Darksonn** [comment]
I would generally want to encourage people to enable all features for their tests. Could we make it show a warning that some tests did not run?

**Comment by kaimast** [comment]
Yeah it would be better if there was a warning or it force-enables all features when you run `cargo test`. Not sure how to do that though, but I'll try to take a look.

**Comment by taiki-e** [comment]
I would prefer to cause an error if the `full` feature is not specified, [like `tokio` crate does](https://github.com/tokio-rs/tokio/blob/master/tokio/tests/_require_full.rs).

**Comment by kaimast** [comment]
I changed this commit request to do what @taiki-e suggested.

**Review by taiki-e — APPROVED** [review]
Thanks!

**Pull request merged**
