### PR TITLE
feat: low-level probes

### PR DESCRIPTION
**Pull request by crepererum**
I'm opening this mostly to see if there's interest in such a feature. If there's a agreement, we can bikeshed the probe names and potential documentation that should come with them.

## Motivation
Linux [perf] is a very powerful tool to understand the performance of an app. While it knows about threads, the tokio tasks are completely opaque to it and hence you'll have a hard time reading the `perf script` output.

## Solution
Add [SystemTap SDT] probes for task polling. See https://github.com/crepererum/tokio2chrome for an example on how to use the probes. This system can later be extended by dtrace probes, which are supported by MacOS and Co.

[perf]: https://perf.wiki.kernel.org/index.php/Main_Page
[SystemTap SDT]: https://sourceware.org/systemtap/wiki/AddingUserSpaceProbingToApps

### CODE REVIEW

**Comment by Noah-Kennedy** [comment]
This seems like it might be quite useful, but it probably needs a lot of discussion before we stabilize it. I think gating this behind `--cfg tokio_unstable` would be a good idea.

**Comment by carllerche** [comment]
@crepererum I need to get more familiar with probes. How do they work with `perf`?

**Comment by crepererum** [comment]
@carllerche have a look at https://github.com/crepererum/tokio2chrome , esp. the `setup_*.sh` and `record.sh` scripts. IMHO it's a bit fiddly because you need to register the probes GLOBALLY before you can use them with `perf record`. I don't really understand why this is required on Linux.

**Comment by Darksonn** [comment]
I don't think we have the review bandwidth to understand what a change like this entails right now. Until then, I think the right place for this suggestion would be an issue rather than a PR.

**Pull request closed without merging**
