### PR TITLE
chore: prepare Tokio v1.8.4

### PR DESCRIPTION
**Pull request by hawkw**
# 1.8.4 (November 15, 2021)

This release backports a bug fix from 1.13.1.

### Fixed

- sync: fix a data race between `oneshot::Sender::send` and awaiting a
  `oneshot::Receiver` when the oneshot has been closed (#4226)

### CODE REVIEW

**Comment by hawkw** [comment]
Ugh, the build's failing because there's other stuff that hasn't been backported to the LTS branch, that's cool.

**Comment by hawkw** [comment]
Note that it was also necessary to backport #4186 and #3988 in order to get CI to pass on the v1.8.x branch.

**Comment by Noah-Kennedy** [comment]
For time audit issue: https://github.com/tokio-rs/tokio/commit/d4848a9e2ee3a5bb57b531b2996d5aba26ea463b

**Comment by hawkw** [comment]
> For time audit issue: [d4848a9](https://github.com/tokio-rs/tokio/commit/d4848a9e2ee3a5bb57b531b2996d5aba26ea463b)

Thanks for finding that <3

**Review by Noah-Kennedy — APPROVED** [review]
Looks good!

**Comment by Noah-Kennedy** [comment]
FreeBSD is also borked

**Comment by Darksonn** [comment]
The borked tests were fixed in #3952 on master.

**Comment by hawkw** [comment]
> The borked tests were fixed in #3952 on master.

Thanks, I'll grab that commit as well.

**Comment by hawkw** [comment]
In order to get the macros build tests to pass I had to basically cherry-pick every `tokio-macros` change since 1.2.0 and then bless slightly diffferent compiler output for some reason...I don't think this is a problem, because we're not going to release a LTS version of `tokio-macros` from this branch?

**Comment by Darksonn** [comment]
The tokio-macros crate has its own tags for its previous releases.

**Pull request merged**
