### PR TITLE
v0.1.x: Fix `UdpFramed` with regards to `Decode`

### LINKED ISSUE #1443: udp: `UdpFramed` violates Decode impl contract
Note: This is an issue that is in 0.1.x and in 0.2.x. Any fix should be backported.

`UdpFramed` violates the decode contract by not attempting to continue decoding past the first discrete item if there is more data in the buffer. 

Correct Framed implementation https://github.com/tokio-rs/tokio/blob/v0.1.x/tokio-io/src/framed_read.rs#L199

and incorrect https://github.com/tokio-rs/tokio/blob/v0.1.x/tokio-io/src/framed_read.rs#L199

This is fixable by just looping and calling decode until None is returned. This is fine since udp datagrams contain all the bytes and there will never be more bytes for that "buffer". This would allow a user to use something like the lines codec with udp where multiple lines are packed into the datagram.

### PR DESCRIPTION
**Pull request by JohnDoneth**
Should (fix) #1443 in the v0.1.x branch.

`UdpFramed` now attempts to continue decoding past the first discrete item if there is more data in the read buffer. I added a test for this that sends a packet with 3 lines and tests for the successful decoding of each item in turn.

### CODE REVIEW

**Comment by LucioFranco** [comment]
@carllerche any idea why we are getting this failure on min supported version?

**Comment by taiki-e** [comment]
@LucioFranco  Perhaps due to https://github.com/tokio-rs/tokio/issues/1369

**Comment by LucioFranco** [comment]
@taiki-e ah yeah...I should get to reviewing those PRs.

**Comment by dekellum** [comment]
@JohnDoneth if you still pursuing this PR, try merging with current v0.1.x branch, for hope of passing CI?

**Comment by LucioFranco** [comment]
@JohnDoneth thanks for this! Is the other PR ready to review/merge into master?

**Comment by JohnDoneth** [comment]
@LucioFranco of course, and yes it's ready!

**Pull request merged**
