### PR TITLE
Address issue 2473

### PR DESCRIPTION
**Pull request by fegies**
## Motivation
Resetting expired timers can cause panics (see #2473)
## Solution

Add an additional check in the remove function fixes this issue.

Please feel free to discard the second commit if you think it is incorrect / correct me if I put the test in the wrong location.

### CODE REVIEW

**Comment by fegies** [comment]
Rebased onto master

**Comment by jxs** [comment]
> The DelayQueue should not try to remove things from the wheel that are not in the wheel.

ah sorry, I thought it was supposed to as the doc states [`the function panics if key is not contained by the queue.`](https://docs.rs/tokio/0.2.21/tokio/time/struct.DelayQueue.html#panics-2)

**Comment by Darksonn** [comment]
Well, the `DelayQueue` distributes the timeouts into two collections, namely `wheel` and `expired`, so just because the key is in the `DelayQueue`, that does not mean that it is also in the wheel.

**Comment by fegies** [comment]
> Well, the `DelayQueue` distributes the timeouts into two collections, namely `wheel` and `expired`, so just because the key is in the `DelayQueue`, that does not mean that it is also in the wheel.

Which is the source of the problem causing the panic.

I can move the test to reset_at if you think this is more appropriate (should work either way)

**Comment by Darksonn** [comment]
Yeah, I think it is better to have `DelayQueue` use the api as exposed by the wheel, and have the check in `reset_at` instead.

**Comment by fegies** [comment]
Replaced the fix commit with a check in the DelayQueue

**Pull request merged**
