### PR TITLE
teach the tokio::test macro to fail tests after a configurable timeout

### PR DESCRIPTION
**Pull request by tdyas**
## Motivation

I was writing tests for a personal project using tokio. One of the tests hung indefinitely while awaiting a receive on a mpsc channel. While I could just add timeouts for specific call sites in the test that can hang, I believe it would be more ergonomic to ensure that tests never hang indefinitely.

## Solution

Add a `timeout = N` argument to time out async tests after N seconds if they do not return to the test harness. This change ensures that async tests cannot hang indefinitely.

Open questions:

1. Should milliseconds or another time unit be used for the `timeout` argument?

2. Does `tests-build` need to be updated? (I see compile error tests there that may need to be updated.)

3. I still need to add documentation to the PR for this change.

### CODE REVIEW

**Comment by tdyas** [comment]
Since the initial submission of this PR, I've modified it to take the timeout in two different ways:

* `timeout = MILLISECONDS`, e.g. `timeout = 500`
* `timeout = DURATION_STRING` (parsed by [humantime::parse_duration](https://docs.rs/humantime/1.3.0/humantime/fn.parse_duration.html), e.g. `timeout = "500ms"`

**Comment by carllerche** [comment]
Thanks for doing the initial work on this and I apologize for the delay in responding.

We are going to pass (for now at least).

Adding a timeout would be something done without any prior art (afaik) and nobody on the tokio team seems to be a strong +1 to the idea. Given that, I think the idea of test timeouts should be proven out separately before it is considered in Tokio.

On a personal note, I am not a fan of adding timing to tests due to how they make tests brittle (especially on CI).

**Comment by cgorski** [comment]
FYI - For integration testing having a timeout on tests is extremely useful. There are scenarios in CI where I would rather the tests be brittle and err on the side of failure then allow code to go out with slow or hanging response.

**Comment by de-vri-es** [comment]
I don't think that timeouts on tests are a new concept or unproven.. Plenty of test frameworks/test runners support it:

Boost: www.boost.org/doc/libs/latest/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref/decorator_timeout.html
pytest: https://pypi.org/project/pytest-timeout/
JUnit: https://docs.junit.org/6.0.2/writing-tests/timeouts.html
MSTest: https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.timeoutattribute?view=mstest-net-4.0
NUnit: https://docs.nunit.org/articles/nunit/writing-tests/attributes/timeout.html
jest: https://jestjs.io/docs/next/jest-object#jestsettimeouttimeout
cmake: https://cmake.org/cmake/help/v3.8/prop_test/TIMEOUT.html
...

And also for Rust, with a combined downloads of ~67 million:
ntest: https://crates.io/crates/ntest
rstest: https://crates.io/crates/rstest

Having an easy way to set a timeout, without having to wrap your entire test body would be nice:

```rust
#[tokio::test]
async fn my_test() {
    tokio::time::timeout(Duration::from_secs(5), async {
        // Actual test goes here
    }).await.unwrap()
}
```

Using the test attribute is so much cleaner:

```rust
#[tokio::test(timeout = 5000)]
async fn my_test() {
    // Actual test goes here
}
```

I regularly do the first to ensure my tests will fail rather than hang if I mess up some tricky async synchronization detail, and I would love to be able to just use the `tokio::test` attribute without an extra proc-macro dependency.

**Comment by Darksonn** [comment]
Timeouts are out of scope for `#[tokio::test]`. All that function does is be a short-hand for `#[test] #[tokio::main]` with a different default runtime configuration. It's not a test runner nor a test framework.

I would suggest using `#[tokio::test]` together with a test runner that supports timeouts, for example [cargo nextest](https://nexte.st/docs/features/slow-tests/).

**Comment by de-vri-es** [comment]
Why is it out of scope? Adding support for a timeout is super useful, and it doesn't require any new dependencies.

And test runners are not async aware, so they can't apply a timeout as cleanly as `tokio` can. They would need to fork off a subprocess to be able to cleanly abort it. But when you know you're in an `async fn` you can just apply a timeout on the future.

**Comment by Darksonn** [comment]
Because timeouts aren't supported by the normal `#[test]` macro.

As for Tokio being able to apply a timeout more cleanly. In one way that's true. But it's also true that this is an imperfect timeout. If the task blocks the thread, the timeout will not actually work.

**Comment by de-vri-es** [comment]
> Because timeouts aren't supported by the normal `#[test]` macro.

But `#[tokio::test]` isn't `#[test]`, so why is this a problem? 

> As for Tokio being able to apply a timeout more cleanly. In one way that's true. But it's also true that this is an imperfect timeout. If the task blocks the thread, the timeout will not actually work.

Sure, but this should fall under normal expectations of a tokio timeout. It shouldn't be a surprise to anyone.

**Comment by Darksonn** [comment]
We're not building a test runner here. The `#[tokio::test]` macro intentionally is the same as `#[tokio::main]` + `#[test]`, with the one exception that it uses the current-thread runtime instead of the multi-threaded one.

**Comment by de-vri-es** [comment]
I don't see what making test runners has to do with this. This can be totally implemented in the `#[test]` macro without creating a test runner. As this PR already did.

And okay, I get that the current implementation of `#[tokio::test]` is the same as `#[tokio::main]` + `#[test]` (with a different default runtime).

The question is: why can't it also be "+ optionally wrap the body in a `tokio::timeout`"?

So far the responses just seem to be "because we don't want to", which gives the feeling that hasn't been seriously considered. Even though multiple users indicate they find it a very useful feature.

While it's valid for maintainers to make choices that go against the wishes of users, it's generally nice if they can at-least show they do their best to see the users point of view too.

**Comment by Darksonn** [comment]
If I add the feature, I have to support it forever. I'm the one who has to reply the inevitable bugreport when someone notices that timeouts don't work for them because they're blocking the thread. You may say that it should fall under normal expectations of a timeout, but I can assure you not everyone will agree when it comes to a test runner.

If someone ever convinces the stdlib to add timeouts to `#[test]` then it's probably going to have slightly different semantics. For example, maybe `cargo test` has some way to let you disable timeouts on all tests, but because Tokio's `timeout = xxx` was implemented first, that `cargo test` feature to disable timeouts on all tests probably does not work on our `timeout = xxx` annotation. It might be a breaking change to make ours work with it.

Or maybe we added timeouts with `#[tokio::test(timeout = 0.5)]` syntax, whereas stdlib used `#[test(timeout = 500ms)]` syntax. Now Tokio doesn't match stdlib for no reason.

On top of that, there is also the possibility of scope creep. Timeouts are pretty unreliable, since if the test runs on in parallel with a million other tests, a test that normally takes milliseconds could take 5 seconds. Yes I've seen it happen. So obviously we should have retries too, right? Should those retries sleep for some amount of time between runs? Should that sleep be constant or exponential backoff? And if we have a retry feature for tests, then people probably expect that they can also use it to retry tests that fail with a panic/error rather than a timeout. Maybe we only want to retry on specific panic messages?

This is what I meant with writing a test runner. These are all great questions, and I don't want to be the one to answer them. There can be a third-party crate that provides a better `#[tokio::test]` macro with more features.

**Comment by de-vri-es** [comment]
Thanks for going in more detail. I appreciate that.

Of course, I still don't agree with the conclusion. I do understand the desire to be compatible with any future syntax `#[test]` might use. On the other hand, if tokio sets a precedent, it's an important enough library that `std` would probably consider compatibility for it's own syntax.

And scope creep can be kept under control.

But anyway, people can disagree. Thank you for taking the time to reply.

**Pull request closed without merging**
