### PR TITLE
impl AsyncWrite for std::io::Cursor

### PR DESCRIPTION
**Pull request by sdroege**
Based on the implementation from the futures crate.

### CODE REVIEW

**Comment by sdroege** [comment]
See https://github.com/rust-lang-nursery/futures-rs/issues/1510 for a behaviour problem with this implementation.

**Comment by taiki-e** [comment]
Note that futures will probably change implementations: https://github.com/rust-lang-nursery/futures-rs/pull/1936

**Comment by sdroege** [comment]
> Note that futures will probably change implementations: [rust-lang-nursery/futures-rs#1936](https://github.com/rust-lang-nursery/futures-rs/pull/1936)

Yeah, I just saw and I'm in the progress of updating. Funny coincidence that this happened at the same time I noticed the missing impl here :)

**Comment by sdroege** [comment]
Updated accordingly but with copy&paste instead of the macro. I assume there's a reason why there's no macro used for the existing things and also `AsyncRead`

**Pull request merged**
