### PR TITLE
Support UnixDatagram framed transport and dgram futures on connected …

### PR DESCRIPTION
**Pull request by glebpom**
## Motivation

`UnixDatagram` supports `connect` and `pair` methods, which are used to define the remote address explicitly, and avoid sending/receiving the remote address. Currently, there are no `Framed` and `send_dgram`/`recv_dgram` methods, which work with the connected `UnixDatagram`s. This is especially a problem with `unnamed` pair, where the remote address is generally not available.  

## Solution

This PR adds new `framed` implementation: `UnixDatagramConnectedFramed`. It works with connected `UnixDatagram` and doesn't deal with a remote address. 
Also, two new methods are added: `recv_dgram_from` and `send_dgram_to`. They behave the same as `recv_dgram` and `send_dgram`, which are now deprecated. `rust` std lib defines the naming for datagram protocols, and it should be preserved for futures. Unfortunately, previously the naming was confusing.
Two additional new methods were introduced for connected variants: `recv_dgram2` and `send_dgram2`.

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for doing this and sorry for the delay. It looks like you are trying to make multiple changes in this PR (work on send / recv as well as add a framed implementation). I think a good way forward would be to split this work into multiple PRs. We can start with send / recv and I will punt of the framed impl initially.

I'm not exactly following your description. Could you clarify this?

> rust std lib defines the naming for datagram protocols, and it should be preserved for futures.

In general, we try to match the std API as much as possible. I do not see a `dgram` fn in `std`, so it makes sense to drop that in `tokio-uds`. So, instead, we probably should have fns named: `recv`, `recv_from`, `send`, and `send_to`.

As for the arguments to the function, using `AsRef<[u8]>` and `AsMut<[u8]>` is a relic of a very early version of Tokio. Instead, we should take `T: Buf` and `T: BufMut` (defined in the `bytes` crate).

**Comment by glebpom** [comment]
Thanks for the response. 

Ok, let's start from `send` / `recv`. I also see exactly the same naming in `tokio-udp`. Could we fix both?

**Comment by Ralith** [comment]
It looks like the naming has been sorted out in tokio 0.2. @glebpom, would you like to update the framing helper?

**Comment by Darksonn** [comment]
This PR is for the old v0.1 version of the codebase, so I am closing it. Feel free to open a new issue regarding framing of `UnixDatagram` if you are still interested in this feature.

**Pull request closed without merging**
