### PR TITLE
chore: update futures-preview to 0.3.0-alpha.19

### PR DESCRIPTION
**Pull request by taiki-e**
~~Depends on https://github.com/carllerche/loom/pull/70.~~
Blocked on https://github.com/carllerche/loom/pull/71 and the next release of loom.

### CODE REVIEW

**Comment by taiki-e** [comment]
I'll be offline, so closing this. Once a new version of loom released and this reopend, CI should pass.

**Comment by jonhoo** [comment]
The loom PR has now landed. I think we still need a new release before this can land though? @carllerche

**Comment by taiki-e** [comment]
Oh, the comment mentions only the loom PR, but in fact, it needs the next release.

**Comment by carllerche** [comment]
Loom is out.

**Comment by carllerche** [comment]
Bumped Ci.

**Pull request merged**
