### PR TITLE
rt: blocking runtime doesn't reponse shutdown flag

### PR DESCRIPTION
**Pull request by bigdogs**
We should check the shutdown flag before the next iteration to interrupt the execution asap, the current implementation doesn't respond to shutdown until queue cleans

### CODE REVIEW

**Comment by Darksonn** [comment]
Hi, thank you for the PR. I missed it when you originally submitted it.

Your PR causes the following test to fail:

https://github.com/tokio-rs/tokio/blob/72993044e6d19d33e46966894e2a7cea4cfa1c4d/tokio/tests/rt_handle_block_on.rs#L195-L210

**Comment by Darksonn** [comment]
According to the test it seems like we (try to) guarantee that tasks spawned before shutdown will complete, but if we really guaranteed that, then #4296 wouldn't be necessary. I don't really understand what's going on with that.

**Comment by Darksonn** [comment]
Any updates on this? If you remove the faulty test, then I would be happy to merge this.

**Comment by bigdogs** [comment]
> Any updates on this? If you remove the faulty test, then I would be happy to merge this.

oh, Sorry I've been busy with other projects, I'll find time this weekend to work on this :)

**Comment by bigdogs** [comment]
there exists other test case failed which I can't figure out why.  :(,  maybe the test case also consider all spawned task should be executed even if runtime is shutdown.  I'll close this pull request as I thinks is just a design choice not a bug :)
```rust
    #[test]
    fn pool_shutdown() {
        loom::model(|| {
            let pool = mk_pool(2);

            pool.spawn(track(async move {
                gated2(true).await;
            }));

            pool.spawn(track(async move {
                gated2(false).await;
            }));

            drop(pool);
        });
    }
```

**Pull request closed without merging**
