### PR TITLE
doc: fix a few broken links by using rustdoc

### PR DESCRIPTION
**Pull request by xliiv**
Also, the link for `driver` is removed because `driver` is now `pub(crate)`, so can't be used in docs.
 

## Motivation
Make doc's links more resistant.

## Solution
Delagates doc's links resolution to [`rustdoc`](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md).
 
Refs: #1473

### CODE REVIEW

**Comment by xliiv** [comment]
Any idea how to rephrased this

> The DelayQueue is backed by the same hashed timing wheel implementation as Timer as such, it offers the same performance benefits. See Timer for further implementation notes.

in https://docs.rs/tokio/0.2.18/tokio/time/struct.DelayQueue.html#implementation

since according to

```shell
git log 27e5b41067d01c0c9fac230c5addb58034201a63`
```
> * `tokio::timer::Timer` is renamed to `Driver` and made private.

**Comment by Darksonn** [comment]
How about this? This leaves it a bit more ambiguous, but that's fine for now.

> The `DelayQueue` is backed by a separate instance of the same timer wheel used internally by Tokio's standalone timer utilities such as `delay_for`. Because of this, it offers the same performance and scalability benefits.
>
> State associated with each entry is stored in a `slab`. This amortizes the cost of allocation, and allows reuse of the memory allocated for expired entires.

I also changed a sentence in the following paragraph that I thought was a bit awkward.

**Comment by xliiv** [comment]
> How about this?

Sounds good, though i'm still learning `Tokio`, so i don't feel like authority here.
So should I simply use it or we're waiting for others opinions?

**Comment by Darksonn** [comment]
Just go for it. We can always change it later if someone thinks it should be changed.

**Comment by Darksonn** [comment]
Can you merge Tokio's master branch? That should fix the FreeBSD ci.

**Comment by xliiv** [comment]
> Can you merge Tokio's master branch? That should fix the FreeBSD ci.

sure, done

**Comment by xliiv** [comment]
> Do you have any other parts of the doc you want to change, or is this ready to merge?

In short
ready to merge

In long
In next step I'll replace `methods`, but this needs a change in `rustdoc`.
After `rustdoc` is changed, I'll create a new MR with updated methods, ok?

**Pull request merged**
