### PR TITLE
sync: rename async-traits feature to sink

### PR DESCRIPTION
**Pull request by taiki-e**
## Motivation

This feature is currently only relevant for futures-sink dependency, so it is probably clearer to use this name.

cc #1210
Related: #1439

### CODE REVIEW

**Comment by carllerche** [comment]
Part of the reason for putting `Stream` implementations behind a feature flag is that, at some point, `Stream` will be moved to `std` (for generators). By using an optional feature flag in sub crates, we can avoid a breaking change to remove the implementation and dependency.

That said, perhaps it is an overeager optimization. I would be interested in hearing what others think.

/cc @tokio-rs/maintainers

**Comment by taiki-e** [comment]
> Part of the reason for putting `Stream` implementations behind a feature flag is that, at some point, `Stream` will be moved to `std` (for generators).

I think this depends on GAT... In addition, futures-core may break other things at that time.

**Comment by seanmonstar** [comment]
I don't love the `async-traits` name... What if it were split to `stream` and `sink`?

**Comment by carllerche** [comment]
I will punt to @tokio-rs/maintainers consensus :)

**Comment by LucioFranco** [comment]
I like `stream` and `sink` feature flag names. I think we should follow the same pattern that futures-rs uses for feature flag names.

**Comment by LucioFranco** [comment]
I like `stream` and `sink` feature flag names. I think we should follow the same pattern that futures-rs uses for feature flag names.

**Comment by taiki-e** [comment]
If we split `async-traits` into `sink` and `stream`, which feature should `FusedFuture` belong to?

**Comment by LucioFranco** [comment]
@taiki-e just `future`?

**Comment by ipetkov** [comment]
I'm also fine with having `sink` or `stream` feature flags which turn on the appropriate `impl`s. We could also have `async-traits` as a convenience feature which turns on `sync` + `stream` + ... but I'm not sure if we need it now or we should add it later (if at all)

**Comment by carllerche** [comment]
Closing due to inactivity. We will revisit all the feature flags / dependencies holistically before the final.

**Pull request closed without merging**
