### PR TITLE
Update examples to return `Result`

### PR DESCRIPTION
**Pull request by JohnDoneth**
I have updated the existing updated examples to use the following main signature as requested in #1278.
```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn Error + Send + Sync>> {
   ...
}
```

### CODE REVIEW

**Comment by carllerche** [comment]
So, this was kind of on hold to avoid requiring `Send + Sync`... There is a strategy by which we can do this, but there are missing bits in tokio-threadpool for now.

**Comment by carllerche** [comment]
I will see if I can get the missing bits done today or tomorrow, then we can move forward with this.

**Comment by JohnDoneth** [comment]
> I will see if I can get the missing bits done today or tomorrow, then we can move forward with this.

Sounds good, I'll be glad to refactor when the changes hit :+1:

**Comment by carllerche** [comment]
@JohnDoneth you should be able to remove `Send + Sync` now :+1:

**Comment by JohnDoneth** [comment]
@carllerche This should be good to go, let me know if you would like any additional changes.

**Pull request merged**
