### PR TITLE
Bump `signal-hook-registry` version

### PR DESCRIPTION
**Pull request by VictorBulba**
See #3804

### CODE REVIEW

**Comment by Darksonn** [comment]
We usually only make minor bumps to dependencies if Tokio _needs_ the new version to work, since it gives more flexibility to users by allowing them to use both the old and new version. At a first glance, that doesn't seem to be the case here?

**Comment by VictorBulba** [comment]
You mean 1.4 better than 1.4.0? This will work, I just noticed that most of the dependencies in tokio's Cargo.toml have a patch specified.

**Comment by Darksonn** [comment]
No, I meant making the change at all.

**Comment by VictorBulba** [comment]
> No, I meant making the change at all.

Ok, this change is related to the issue that I consider as a bug/undocumented behavior. Then yes, it is not a simple dependency update.

**Comment by Darksonn** [comment]
I'm not necessarily opposed to this — I haven't fully understood the original issue. 

@ipetkov thoughts?

**Comment by ipetkov** [comment]
I'm weakly opposed to doing this bump here and now:

* we don't *need* to do this bump as any consumers can get the latest version of `signal_hook` via `cargo update`
* if the `signal_hook` changes happen to break someone's application, they can easily pin to a slightly older version and get the desired behavior back
* if we bump the version here, then someone whose application is broken will also have to roll the tokio update back, or we might need to yank the version, etc

**Comment by Darksonn** [comment]
Closing due to @ipetkov's comments. Be aware that this being merged does not prevent you from using the changes to `signal-hook-registry` as the new version is semver-compatible with the one Tokio depends on.

**Pull request closed without merging**
