### PR TITLE
Fix document on watch

### PR DESCRIPTION
**Pull request by takassh**
## Motivation

`tokio::sync::watch` should be a single-producer,  multi-consumer channel afaik.
Actually, it can't be cloned.
So the current documentation may lead misunderstanding.

## Solution

Fixed documentation

### CODE REVIEW

**Comment by mox692** [comment]
Thanks for the PR.

`Clone` of `watch::Sender` was introduced in [this PR](https://github.com/tokio-rs/tokio/pull/6388), and that change was shipped in the [latest v1.37.0 release](https://github.com/tokio-rs/tokio/releases/tag/tokio-1.37.0).

If you are not using v1.37.0 tokio, then you probably cannot use Sender's Clone.

**Comment by takassh** [comment]
@mox692 
Ah thank you!
then this document may be wrong?
https://tokio.rs/tokio/tutorial/channels#tokios-channel-primitives

which says `watch: single-producer, multi-consumer. Many values can be sent, but no history is kept. Receivers only see the most recent value.`

Can I fix it?

**Comment by mox692** [comment]
Thanks, that correction would be helpful.

**Comment by takassh** [comment]
Thanks for the quick response!
let me close this.

**Pull request closed without merging**
