### PR TITLE
Remove `rust-toolchain` file

### PR DESCRIPTION
**Pull request by LucioFranco**
Since we can use rust stable now :)

### CODE REVIEW

**Comment by carllerche** [comment]
I guess I'll merge this when 1.39 is available on rustup?

**Comment by mmstick** [comment]
It should be kept so that we know which version of a crate is supported by what version of Rust.

**Comment by CryZe** [comment]
rustup defaults to stable without the toolchain file. So you do know that if the toolchain file is removed that the stable toolchain should be able to compile it. So why would you want to keep it?

**Comment by mmstick** [comment]
The idea is to specify `1.39.0` in the `rust-toolchain` file, declaring that it is the minimum-supported version of Rust compatible with the crate. Honestly, it should be a mandatory field in `Cargo.toml`, but it's not, so here we are.

I write software for a Linux distribution, which depends on crates being compatible with the version of Rust in the distribution repositories, if I expect to be able to package them for it. Linux distributions rarely update their Rust packages on a new Rust release, so they're often a few releases behind. As an example, the maximum version of Rust supported on Ubuntu 18.04 is 1.36.0.

Eventually it will support 1.39.0, and this project may decide to move the compiler goalpost to 1.40 or 1.41 by then. So when it does, it's always nice to know which versions of a crate are compatible with what release, so I don't have to tamper with trial and error to find a version that's compatible. It's also useful for semantic versioning, considering it's a breaking change to update the minimum requirement of Rust compiler releases.

**Comment by CryZe** [comment]
> considering it's a breaking change to update the minimum requirement of Rust compiler releases.

It's not actually considered a breaking change officially. In general I supported the idea of MSRV in Cargo.toml or so, but using rust-toolchain for it, is kind of questionable, as that forces me to have every old toolchain installed on my PC, instead of just stable (when stable should be able to compile all old code anyway).

**Comment by taiki-e** [comment]
(Hmm, it seems to need to rebase. I tried to do it with merge commit but it didn't work.)

**Comment by CryZe** [comment]
This PR only removes the rust-toolchain file. master already changed it to just contain "stable". So you probably should either just recreate the commit removing the rust-toolchain file based on master, or just close this PR.

**Comment by taiki-e** [comment]
> The idea is to specify `1.39.0` in the `rust-toolchain` file, declaring that it is the minimum-supported version of Rust compatible with the crate. Honestly, it should be a mandatory field in `Cargo.toml`, but it's not, so here we are.

MSRV should be checked with CI [like 0.1 branch](https://github.com/tokio-rs/tokio/blob/v0.1.x/azure-pipelines.yml#L77_L87).
Also, I agree to remove rust-toolchain because [test may not run on MSRV](https://github.com/tokio-rs/tokio/blob/v0.1.x/azure-pipelines.yml#L82-L87).




> This PR only removes the rust-toolchain file. master already changed it to just contain "stable". So you probably should either just recreate the commit removing the rust-toolchain file based on master, or just close this PR.

Yeah, I'll send an alternative pr.

**Comment by taiki-e** [comment]
Closing in favor of #1748 (I should have merged this before merging #1747, sorry @LucioFranco)

**Comment by carllerche** [comment]
@mmstick CI should include a test run using the declared minimum supported version. Including a `rust-toolchain` file will force all Tokio devs to download a full rust toolchain at that version (potentially GB).

IMO, we should get rid of the toolchain file and update the CI run to specify 1.39 as the min rust version.

**Pull request closed without merging**
