### PR TITLE
Remove some uses of mem::uninitialized

### PR DESCRIPTION
**Pull request by Darksonn**
Please see https://github.com/tokio-rs/tokio/pull/1295#issuecomment-683766262. Note that I am not familiar with this code.

@RalfJung Is there an easy way to try the version of Rust that will panic at runtime when encountering this UB?

### CODE REVIEW

**Comment by RalfJung** [comment]
>  Is there an easy way to try the version of Rust that will panic at runtime when encountering this UB?

Hm... we have a try build with ID 41997647ba6a77908f6ef64401414feb00bccf16; maybe you can install that using https://github.com/kennytm/rustup-toolchain-install-master/ ?

**Comment by Darksonn** [comment]
I tried running the test suite with miri, which seemed easier, but that failed due to UB in an old version of futures :upside_down_face: 
```
error: Undefined Behavior: type validation failed: encountered 0x0000000000000001, but expected a function pointer
   --> /home/alice/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:61:19
    |
61  |         let get = mem::transmute::<usize, _>(0x1);
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type validation failed: encountered 0x0000000000000001, but expected a function pointer
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
```

**Comment by Darksonn** [comment]
Using the build ID results in another failure when compiling libc.
```
$ cargo +41997647ba6a77908f6ef64401414feb00bccf16 test --all-features
   Compiling cfg-if v0.1.10
   Compiling autocfg v1.0.0
   Compiling libc v0.2.73
   Compiling futures v0.1.29
   Compiling maybe-uninit v2.0.0
   Compiling lazy_static v1.4.0
   Compiling log v0.4.8
   Compiling semver-parser v0.7.0
error: unknown codegen option: `embed-bitcode`

error: unknown codegen option: `embed-bitcode`

error: unknown codegen option: `embed-bitcode`

error: could not compile `cfg-if`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: unknown codegen option: `embed-bitcode`

error: unknown codegen option: `embed-bitcode`

error: unknown codegen option: `embed-bitcode`

error: unknown codegen option: `embed-bitcode`

error: unknown codegen option: `embed-bitcode`

error: build failed
```

**Comment by RalfJung** [comment]
@Darksonn ah, new cargo is incompatible with old nightly rustc. In an hour or two, build ID 8873b76aa307bd680346d790161bb6416806b5c1 should be available and fix that problem.

**Comment by carllerche** [comment]
What do you want to do about this?

**Comment by carllerche** [comment]
Closing due to inactivity. This also targets v0.1 which is pretty old at this point.

**Pull request closed without merging**
