### PR TITLE
net: add epollhup test

### PR DESCRIPTION
**Pull request by Darksonn**
Fixes: #3879

### CODE REVIEW

**Comment by Darksonn** [comment]
It seems like the behavior is different on mac.

**Review by Thomasdezeeuw — APPROVED** [review]
LGTM.

@Darksonn have you mean able to reproduce the issue in https://github.com/tokio-rs/tokio/issues/3879? Or is this just checking all errors. @bnoordhuis suggested in https://github.com/tokio-rs/tokio/issues/3879#issuecomment-869614870 that this error might not be fatal.

**Comment by Darksonn** [comment]
Well, the test I added fails without the change. I didn't try other things than the test.

**Review by carllerche — APPROVED** [review]
Looks good to me!

**Comment by Darksonn** [comment]
We already do this for TCP as seen [here](https://github.com/tokio-rs/tokio/blob/d35ff7064f2e0f90764487f45606dba57f3beaba/tokio/src/net/tcp/stream.rs#L137-L153), however when I added the test for TCP it didn't seem to work.

**Comment by carllerche** [comment]
The TCP test might require setting linger to 0. Either way, we can merge this I think.

**Pull request merged**
