### PR TITLE
docs: document that parking_lot is enabled by full

### PR DESCRIPTION
**Pull request by omjadas**
## Motivation

The current docs only specify that public API features are enabled using full, this is not correct.

## Solution

Update documentation to be in line with actual features.

### CODE REVIEW

**Comment by Darksonn** [comment]
But the `full` feature _does_ enable parking_lot too.

https://github.com/tokio-rs/tokio/blob/cf3206842c0d94ecdaaeb421a58b1c963b627c3d/tokio/Cargo.toml#L31-L44

**Comment by omjadas** [comment]
> But the `full` feature _does_ enable parking_lot too.

Perhaps my wording was not clear enough, I meant that it enables all the public API features except test-util, and also enables parking-lot. Open to suggestions to clear it up, perhaps it could simply become `Enables all features listed below except test-util and tracing`.

**Comment by Darksonn** [comment]
Yes, that would be a better phrasing.

**Comment by omjadas** [comment]
> Yes, that would be a better phrasing.

Done.

**Review by Darksonn — APPROVED** [review]

**Pull request merged**
