### PR TITLE
Include a ~~single-threaded~~ manually built runtime example

### PR DESCRIPTION
**Pull request by vorner**
People ask about this quite often. And I think it is easier than the multi-threaded setup, so it might be a good step to understanding how the things work together.

I plan on writing some documentation describing it for the tokio.rs website.

### CODE REVIEW

**Comment by vorner** [comment]
Well, my example was more to show how to put the things together in case someone needs to tweak it. But I added a note, referencing the „usual“ single threaded runtime.

**Comment by carllerche** [comment]
I should have commented earlier, but this looks good to me. I'm waiting on #308 since this references those APIs.

**Comment by kpp** [comment]
#308 is merged

**Comment by carllerche** [comment]
@vorner would you mind updating this so the links point to the APIs that were shipped (current thread instead of singlethread, etc...).

**Comment by vorner** [comment]
I hope I've found all of them. They are not really links in the web sense, but I think the full paths are enough. I've amended the commit not to clutter the history, but the changes are minimal (just in comments, I also fixed some English that didn't look right).

Should I also go through the web version at https://tokio.rs/docs/going-deeper/building-runtime/?

**Comment by kpp** [comment]
Your example may be rewritten using #308. Please have a look at docs in https://github.com/tokio-rs/tokio/blob/master/src/runtime/current_thread/mod.rs

**Comment by vorner** [comment]
But that's explicitly *not* the point. I even mention that if the user wants to just run everything in a single thread, they should use it, that this example is demonstration how an arbitrary runtime can be composed in case one wants to tweak beyond what the configuration allows.

**Comment by vorner** [comment]
That sounds like a reasonable worry and I'll probably could get to it some time soon. But, do you thing renaming this one (to let's say „manually_built_runtime.rs“) + the comment at the top could solve the problem? Basically, if it never said „single threaded runtime“ anywhere except at the place where it would link to the existing one?

**Comment by kpp** [comment]
> But, do you thing renaming this one

yes

> Basically, if it never said „single threaded runtime“ anywhere 

You PR is named as **Include a single-threaded example** =)

**Comment by vorner** [comment]
> You PR is named as Include a single-threaded example =)

Yes, I know. I meant in the code/comments. You're right about the potential confusion, and I thought of renaming it only after you pointed it out.

**Comment by carllerche** [comment]
This all looks good to me. I wouldn't worry about the second example now. Someone else can contribute if they have time.

**Comment by carllerche** [comment]
Renaming to "manual runtime" is 👍

**Pull request merged**
