### PR TITLE
chore: update pin-project to 0.4

### PR DESCRIPTION
**Pull request by taiki-e**

### CODE REVIEW

**Comment by taiki-e** [comment]
Does the build failure seem to be related to loom 0.2.6?: https://dev.azure.com/tokio-rs/Tokio/_build/results?buildId=2463&view=logs&jobId=4d24a655-b158-5a78-3301-a0ebfcb42049

**Comment by LucioFranco** [comment]
@carllerche ^

**Comment by carllerche** [comment]
I am investigating the CI failure.

**Comment by jonhoo** [comment]
@taiki-e I believe now that https://github.com/tokio-rs/tokio/pull/1608 you should be able to merge this and get passing CI

**Pull request merged**
