### PR TITLE
Add sync::watch:::Receiver::next_changed()

### PR DESCRIPTION
**Pull request by uklotzde**
## Motivation

The current API does not allow to create streams with strict _at-most-once_ semantics.

`sync::watch::Receiver::await_for()` is opinionated, needlessly complex and inconsistent in its behavior. It doesn't compose well in loops.

## Solution

Combine two existing plumbing methods into the new `next_changed()` method. In conjunction with the recently introduced `mark_changed()` method this allows implementing various consumer patterns in a consistent way.

### CODE REVIEW

**Comment by Darksonn** [comment]
This is just the same as this?
```rs
chan.changed().await?;
let val = chan.borrow_and_update();
```

**Comment by Darksonn** [comment]
Wait, actually, it's the same as this:
```rs
chan.changed().await?;
let val = chan.borrow();
```
which does _not_ guarantee that the value is only seen once.

**Comment by Darksonn** [comment]
The motivation for the current shape of `wait_for` was discussed at https://discord.com/channels/500028886025895936/1096899885715963995/1097561944237551656

**Comment by uklotzde** [comment]
If anyone is aware of a strategy on how to combine the existing, public methods to achieve this exact behavior, then I would be keen to know. I didn't find one that works without race conditions and are causing duplicates.

I never understood why `wait_for` is so complex. You can't use it repeatedly in loops because it always yields the initial value immediately.

**Comment by Darksonn** [comment]
This should never print a duplicate:
```rs
loop {
    chan.changed().await?;
    println!("{}", chan.borrow_and_update());
}
```

**Comment by uklotzde** [comment]
My _work-in-progress_ examples for creating asynchronous streams can be found here: https://github.com/uklotzde/discro/blob/19dbc545561e4cda7b2dea04ed68a1a5cd529b5d/src/tokio.rs#L193

**Comment by uklotzde** [comment]
Thanks for the discussion! I just noticed that my proposal contains a race condition that also causes duplicates :see_no_evil:

Looks like we can't get around loading and updating the version twice by invoking `changed()` and `borrow_and_update()` in a row. Acquiring the lock before updating the version is crucial here.

You only need to remember then that `Ref::has_changed()` returns an arbitrary value although it actually is always `true`.

**Pull request closed without merging**
