### PR TITLE
Refactor debounce implementation

### PR DESCRIPTION
**Pull request by NeoLegends**
This addresses the feedback from https://github.com/tokio-rs/tokio/pull/747#pullrequestreview-189619473.

Improved documentation will follow.

### CODE REVIEW

**Comment by carllerche** [comment]
I'm going to revert the original PR (#834) as it broke CI (due to a conflict w/ another PR i believe) and I need to release crates and we still need to tweak the public API. Once that PR lands, could you update this PR to be a take 2?

Sorry for the churn.

**Comment by carllerche** [comment]
Thanks for the work :+1: I'm going to close this due to inactivity and stagnation. If you want to revisit, we can talk about what steps are required to update it to the latest changes on master.

**Comment by NeoLegends** [comment]
So I'm actually in a situation where I'd like to revisit this right now.

Use-case: We receive update events via a `Stream` and want to forward them via Websockets to browser clients. Because the update rate can be quite high, we want to allow the browsers to apply a rate limit to the updates. The websocket server would then wait a fixed time between sending updates and throw away all the others.

**Comment by extremeandy** [comment]
I'm very keen to see `sample` and `debounce` and a whole raft of extensions on streams to bring us closer to feature parity with ReactiveX. Any chance of reviving this?

**Pull request closed without merging**
