### PR TITLE
docs: `tokio::main` macro also supported on `rt`

### PR DESCRIPTION
**Pull request by fl9**
Fixes: #3144
Refs: #2225

### CODE REVIEW

**Review by Darksonn — CHANGES_REQUESTED** [review]
This results in the following annotation:

> This is supported on crate features macros and rt and rt-multi-thread only.

You will probably have to replace the `cfg_*` macros with `#[cfg(...)]` to get around this.

**Comment by fl9** [comment]
What should the annotation look like in the end?

**Comment by Darksonn** [comment]
The annotation you have already added is correct, but the `cfg_rt_multi_thread!` macro also gives it one of those annotations, and this extra annotation is the reason for the problem. You must remove the `cfg_rt_multi_thread!` macro and instead use an `#[cfg(...)]` annotation directly to control when it is compiled. See the definition of the macro for more information on how the annotation is used, or [this article](https://doc.rust-lang.org/reference/conditional-compilation.html).

**Comment by fl9** [comment]
Thanks for your feedback. I changed it such that the annotation looks like

> This is supported on crate feature macros and (crate features rt-multi-thread or rt) only.

I hope this is the right way to express the feature sets `["macros", "rt"]` or `["macros", "rt-multi-thread"]`.

**Comment by Darksonn** [comment]
It produces the following annotation:

> This is supported on crate feature macros and (crate features rt-multi-thread or rt) only.

I suppose that's ok. Note that enabling rt-multi-thread will automatically enable the rt feature, so strictly you could just say `["macros", "rt"]`, but the current approach may be easier to read.

What do you think?

**Comment by fl9** [comment]
Actually, I like both possibilities. Reading the docs, e.g., https://docs.rs/tokio/0.3.5/tokio/index.html#working-with-tasks, one could argue that `["macros", "rt"]` is sufficient as annotation. It would also be more consistent with https://docs.rs/tokio/0.3.5/tokio/runtime/index.html#runtime-scheduler (for example).

On the other hand: If we would go with just `["macros", "rt"]` then `rt-multi-thread` wouldn't be listed anywhere on this page https://docs.rs/tokio/0.3.5/tokio/attr.main.html. Maybe it would make sense to mention `rt-multi-thread` somehow in the paragraph `Multi-threaded runtime` then (like in https://docs.rs/tokio/0.3.5/tokio/runtime/index.html#multi-thread-scheduler) ?

Summarized, I lean towards the more concise annotation `["macros", "rt"]` with optionally mentioning `rt-multi-thread` somewhere in the paragraph https://docs.rs/tokio/0.3.5/tokio/attr.main.html#multi-threaded-runtime.

What is your opinion on this?

**Comment by Darksonn** [comment]
Going for the more concise annotation seems good, especially with the additional text to the paragraph.

Another thing to note is that, if you try to use the macro without enabling `rt-multi-thread`, but use it in a way that selects the multi-threaded executor, then you get a nice error message telling you that you are missing the `rt-multi-thread` feature.

https://github.com/tokio-rs/tokio/blob/3f29212cb7743462451293b65d4bb8b5b4973fc5/tokio-macros/src/entry.rs#L99-L103

If you have enabled `macros` but neither `rt` nor `rt-multi-thread`, you also get a nice message:

https://github.com/tokio-rs/tokio/blob/3f29212cb7743462451293b65d4bb8b5b4973fc5/tokio-macros/src/lib.rs#L261-L273

There's no nice error message if `macros` is missing though, because then we don't depend on the `tokio-macros` crate at all.

**Review by Darksonn — APPROVED** [review]

**Pull request merged**
