### PR TITLE
Sort methods on mpsc::Sender in doc

### PR DESCRIPTION
**Pull request by k-nasa**
## Motivation
close: https://github.com/tokio-rs/tokio/issues/2371

## Solution

Sort methods on mpsc::Sender.

### CODE REVIEW

**Comment by Darksonn** [comment]
The `cfg_time!` macro can't be inside an `impl` block, instead it should have an impl block inside. It seems like you need the method to be inside the impl block to get the ordering right, and to do that, you would have to do this:
```rust
/// ...
#[cfg(feature = "time")]
#[cfg_attr(docsrs, doc(cfg(feature = "time")))]
pub async fn send_timeout(...
```

**Comment by k-nasa** [comment]
@Darksonn Thanks review !
I don't know what happened CI. Can you rerun CI ?

**Comment by Darksonn** [comment]
A merge conflict was apparently introduced by #2372. Can you fix that? That'll also have the side effect of rerunning CI.

**Comment by k-nasa** [comment]
The CI doesn't seem to be down because of this PR change.

**Comment by hawkw** [comment]
The FreeBSD CI failure looks like an unrelated CI issue, I'm restarting it.

**Comment by Darksonn** [comment]
This isn't the only thing failing due to that check, so I'm merging it.

**Pull request merged**
