### PR TITLE
style: simplify statements for readability

### LINKED ISSUE #6977: Some statements can be simplified for readability
We can replace lines like

```rust
format!("The `{}` attribute requires an argument.", name)
```

with

```rust
format!("The `{name}` attribute requires an argument.")
```

to improve code readability and maintainability.

### PR DESCRIPTION
**Pull request by hamirmahal**
Closes #6977

## Motivation

Some lines like

```rust
format!("The `{}` attribute requires an argument.", name)
```

aren't as readable as they could be.

## Solution

We can replace lines like

```rust
format!("The `{}` attribute requires an argument.", name)
```

with

```rust
format!("The `{name}` attribute requires an argument.")
```

to improve code readability and maintainability.

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
This shouldn't cause any user-facing changes.

The goal of this pull request is to improve code readability and developer productivity.

**Review by nurmohammed840 — APPROVED** [review]

**Comment by nurmohammed840** [comment]
Nice!
Did you use any tools for this, or was it done manually?

**Comment by hamirmahal** [comment]
I did! I used `clippy`.

**Review by Darksonn — APPROVED** [review]
Thanks.

**Comment by hamirmahal** [comment]
You're welcome.

**Pull request merged**
