### PR TITLE
Fix a few typos in timer docs.

### PR DESCRIPTION
**Pull request by jasondavies**

### CODE REVIEW

**Comment by jasondavies** [comment]
Seems like an overzealous `e` key? :)

**Comment by tobz** [comment]
I do believe @carllerche was lamenting about his MacBook keyboard getting sticky... :)

@mathstuf I'd say rebase off of this, since your PR has a lot of other bits.

@jasondavies You cool if we went with @mathstuf's PR?

**Comment by jasondavies** [comment]
Sure!

**Comment by jasondavies** [comment]
I think you might have missed a couple under `tokio-timer/` in your rebase?  In any case, I've rebased this PR on latest master in case it's helpful.

**Pull request merged**
