### PR TITLE
io: fix `take` when using evil reader (backport #4428)

### PR DESCRIPTION
**Pull request by carllerche**
Backports #4428 into 1.8.x

### CODE REVIEW

**Comment by carllerche** [comment]
The CircleCI build will fail due to missing configuration. It shouldn't block merging.

**Comment by Darksonn** [comment]
This needs to include #4437.

**Comment by carllerche** [comment]
@Darksonn thanks, I'll pull it in once I wrangle CI.

**Comment by carllerche** [comment]
@Darksonn Ok, I backported the fix as well.

**Review by Darksonn — APPROVED** [review]

**Comment by carllerche** [comment]
Reordering commit before merge.

**Pull request merged**
