### PR TITLE
Signal refactor

### PR DESCRIPTION
**Pull request by ipetkov**
This refactors how Unix signals are dispatched:

* A new signal driver is introduced to be the central receiver of wake events coming from the OS and dispatching the events to any `Signal` listeners
* This will lead to fewer spurious wakups since tasks blocked on a `Signal` instance will only get woken up when their respective signal is received, rather than always being woken up whenever *any* signal is received
* This also leads to using fewer file descriptors. With this change a single file descriptor is needed per driver/runtime rather than requiring duplicating a file descriptor per `Signal` instance

There is an open question regarding how a runtime should be configured given that we're introducing the concept of dependent drivers, in this case `signal` depending on `io` (the dependency was alway there implicitly). For example, using the `process` module on Unix systems requires the `signal` feature, and the `io` feature transitively, but on Windows neither of the modules are required. Should we require that a runtime is explicitly built with all required features, or should turning on a feature transitively enable dependent features?

- on one hand, an explicit configuration avoids issues with implicitly relying on a transitive feature such that if internal refactoring leads to that feature no longer being required, then such code would break
- on the other hand, it potentially leaks out details (e.g. the `process` -> `signal` -> `io` dependency), and subsequent internal refactors could lead to older code relying on more features than they need (e.g. `process` stops requiring `signal`)

### CODE REVIEW

**Comment by ipetkov** [comment]
FWIW I did run the benchmarks before and after the changes on my under-powered machine, but the results would vary wildly in between consecutive runs so I did not bother publishing them here, but happy to if someone would like to see them.

**Comment by carllerche** [comment]
Thanks for getting this done. I did a quick skim, but this is going to take more time to go over closer :) I will look asap.

cc/ @seanmonstar this relates to your I/O driver work as well.

**Review by carllerche — APPROVED** [review]
LGTM :+1: Thanks for making this happen.

**Review by seanmonstar — APPROVED** [review]

**Comment by ipetkov** [comment]
Thanks for the reviews!

Just wanted to mention that @carllerche and I discussed this in the discord and we decided to omit the `enable_signal` method on the runtime builder, and enable the `signal` driver if `io` is enabled (we already have a compile time flag to disable `signal` for those that do not need it), so I will update

**Pull request merged**
