### PR TITLE
v0.1.x: stage -threadpool 0.1.16 -reactor 0.1.10 releases

### PR DESCRIPTION
**Pull request by dekellum**
This merges #1358 to current v0.1.x branch, firstly just to make sure CI is still passing. 

In ad62407, it also bumps the env_logger dev dependency to 0.6. (env_logger 0.7 was releases only two days ago, so 0.6.2 is considered a more conservative choice.) This is just a backport of #1390 (on master).

I plan to make the version bumps and CHANGELOG entries here as well, after confirming CI on the base changes.

### CODE REVIEW

**Comment by dekellum** [comment]
@LucioFranco this is ready, I believe, with everything needed before `merge`, `cargo publish` and `git tag` of these crates.   If this looks good and can happen today, then the dates in the change log will even be correct!  Thanks.

**Comment by LucioFranco** [comment]
I'd like to get a second review from carl then I think we can publish this! Thanks!

**Comment by dekellum** [comment]
@carllerche?  From last comments of #1358 it sounded like this was already pretty much decided upon?

**Comment by LucioFranco** [comment]
@dekellum yup! sorry been busy, I am gonna push this out today. Thank you for all the work, we all very VERY much appreciate it! <3

**Pull request merged**
