### PR TITLE
Close pending connection on proxy exemple 

### PR DESCRIPTION
**Pull request by alborq**
## Motivation
On proxy exemple, if a connection is close from one side, one side stay open, a thread keep infinitly pending. 

Fix : #2406 

## Solution
Close writer after copying totalité of reader

### CODE REVIEW

**Comment by Darksonn** [comment]
Clippy appears to have failed on unrelated parts of the code. Perhaps clippy has had an update? Additionally, MacOS tests failed with [this][1], which seems bad, but also seems unrelated.

[1]: https://gist.github.com/Darksonn/fcfe79c1e49b7495ec0ac968c925b319

**Comment by Darksonn** [comment]
Is this actually what we want? If one direction is not closed by the proxied party, should we not keep it open?

**Comment by alborq** [comment]
TCP say when one side send EOF, exchange is finish, actually EOF is intercept by copy, reason why connect is not close on both side.
I don't thinks keeping an unusable proxy has some interest. 

I rebase asap.

**Comment by Darksonn** [comment]
Hi. If you can make add a merge commit, we can move the PR forward.

**Comment by alborq** [comment]
Sorry for delay, i have merge master. 
I wait test result to move forward.

**Pull request merged**
