### PR TITLE
Reexport tokio_io::IoFuture from tokio crate

### PR DESCRIPTION
**Pull request by kpp**

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for the PR. However, IoFuture and stream should be deprecated. 

I’m going to close this Pr. Would you mind submitting one that deprecated them and indicate to box manually?

**Comment by kpp** [comment]
Well... I find IoFuture very useful when I write the code in my project. I don't like long return types.

**Comment by carllerche** [comment]
You may always define it in your projects (and I do sometimes).

It's being removed as it ended up being more confusing than beneficial in the library. See [here](https://github.com/rust-lang-nursery/futures-rs/issues/228).

**Comment by kpp** [comment]
I don't understand. It is fine to remove .boxed method, but do I really have to implement long return type with `+ send` only because some folks could not read docs?

**Comment by carllerche** [comment]
I would recommend opening an issue on the futures-rs repo. This is more a question of futures related idioms than Tokio related.

**Pull request closed without merging**
