### PR TITLE
[Experiment] Semver trick

### PR DESCRIPTION
**Pull request by MikailBag**
This is **experimental** PR to check whether semver trick would work for Tokio.
Currently, the answer seems to be "yes".

## Motivation
Ideally, this should enable near-100% for Tokio 0.3 and Tokio 1.0 users

## Solution
Implement all "global" parts (executor, time, and io) in terms of Tokio 1.0, reexport IO traits.

### CODE REVIEW

**Comment by MikailBag** [comment]
Test `ping_pong_saturation` hangs. It is probably connected to `block_on`, because I had to replace it with something hacky until #3097 is merged.

**Comment by dekellum** [comment]
Hey, thanks for attempting to navigate this 0.3 to 1.0 upgrade!  :+1: 

I would just suggest that the final proposal/packaging, if this moves forward, would be to release a _tokio-compat_ 0.3.0 crate. Users just opt in to this by replacing _tokio_ dep with it in there Cargo.toml, I believe.  Said another way, I'm not a proponent of the "trick" part of the "Semver trick", which IMO is almost always a risky hack to release as a patch release in any older series of _tokio_ proper. It violates most Semver principals of what kinds of changes are acceptable in a patch release. Even a ≤1.0.0 patch release, given local conventions and maturity of tokio 0.1-0.3.

Or at least that's my 2¢, thanks again!

**Comment by MikailBag** [comment]
@dekellum your concern is reasonable. I don't have strong opinion here. As an additional argument for releasing a separate crate, _some_ breaking changes seem to be unavoidable (e.g. shutdown() on TCP sockets).

Anyway, currently this PR requires some debugging work and can't be merged as is. I'll try to find some time this week.

**Comment by MikailBag** [comment]
I think most of the ecosystem has already migrated to Tokio v1, so this experiment now has little value.

**Pull request closed without merging**
