### PR TITLE
net: Pass SocketAddr by value

### LINKED ISSUE #3122: net: all SocketAddr arguments should be by value
I noticed that, at least, `UdpSocket::poll_send_to` takes the `SocketAddr` by reference.

### PR DESCRIPTION
**Pull request by nylonicious**
## Motivation
Closes #3122.

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks! This is a breaking change, so I will hold off merging for now. We should be forking off 1.0 "soonish" though.

**Comment by nylonicious** [comment]
I also updated one call to `UdpSocket::poll_send_to` in tokio-util, if that will be an issue I'll revert the change.

**Comment by LucioFranco** [comment]
Whats the status on this?

**Comment by Darksonn** [comment]
I think the status is that its blocked on forking off v1.0.

**Comment by taiki-e** [comment]
triage: this is no longer blocked

**Comment by LucioFranco** [comment]
@nylonicious can you rebase then we can get this merged! thanks.

**Review by LucioFranco — APPROVED** [review]

**Comment by LucioFranco** [comment]
Thanks!

**Pull request merged**
