### PR TITLE
chore: use Cirrus CI for ARM

### PR DESCRIPTION
**Pull request by carllerche**
Experiment with using Cirrus CI for ARM instead of Circle.

### CODE REVIEW

**Comment by carllerche** [comment]
It seems like Cirrus ARM does not support IPv6. Thoughts @taiki-e ?

**Comment by taiki-e** [comment]
IIRC, Arm containers are executed in AWS's EKS. And AWS added support for IPv6 [a few weeks ago](https://github.com/aws/containers-roadmap/issues/835#issuecomment-1006804864). So it will probably be available in Cirrus CI in the near future.

**Comment by carllerche** [comment]
@taiki-e Thanks, I reached out to Cirrus (see linked issue above).

**Comment by carllerche** [comment]
This stagnated.

**Pull request closed without merging**
