### PR TITLE
Using workspace dependencies

### PR DESCRIPTION
**Pull request by rodoufu**
## Motivation

I've added workspace dependencies to make it easier to maintain them and avoid having distinct version on workspace members.

### CODE REVIEW

**Comment by Darksonn** [comment]
I've never seen this before. Since what Rust version is this possible?

**Comment by rodoufu** [comment]
> I've never seen this before. Since what Rust version is this possible?

It is available since version 1.64 https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-164-2022-09-22

**Comment by Darksonn** [comment]
Our minimum supported rust version is 1.63.

**Comment by rodoufu** [comment]
I'm closing this due to https://github.com/tokio-rs/tokio/pull/6301#issuecomment-1908362681

**Pull request closed without merging**
