### PR TITLE
Azure Pipelines

### PR DESCRIPTION
**Pull request by rylev**
This adds Azure Pipelines CI to the project.

## Motivation

With Travis seemingly shutting down, @carllerche asked about Azure Pipelines. Here's a work-in-progress of that.
 

## Solution

This is thoroughly work-in-progress. It runs on Linux and macOS but has several failures. In addition it does not use a specific nightly for the thread sanitizer.

### CODE REVIEW

**Comment by carllerche** [comment]
@rylev Thanks for getting this started! I'll be poking around here too. You are obviously further along than me (https://github.com/tokio-rs/tokio/pull/926) :P.

**Comment by carllerche** [comment]
I also found that [diesel](https://github.com/diesel-rs/diesel) has a pretty comprehensive pipelines setup.

**Comment by rylev** [comment]
@carllerche I think we can close this and just use it as a reference for your work on #926. Let me know how I can help push #926 further! 😄

**Comment by carllerche** [comment]
Thanks for getting it started, I ended up copying your stuff + other stuff I found.

Happy to get more help to add missing tasks in the other PR. You should have perm to push to the branch?

**Comment by rylev** [comment]
@carllerche 👍 I'll let you let me know what exactly is missing and will work on the stuff you need help with (so we don't both end up doing the same thing). I _might_ have permission, but I'll let you know if I don't.

**Comment by carllerche** [comment]
@rylev You want to try adding the check only cross compilation bit: https://github.com/tokio-rs/tokio/blob/master/.travis.yml#L104-L106?

**Comment by rylev** [comment]
@carllerche yea sounds great - Will do!

**Comment by rylev** [comment]
@johnterickson FYI ^^

**Pull request closed without merging**
