### PR TITLE
chore: remove redundant field names in struct literals

### PR DESCRIPTION
**Pull request by taiki-e**
rustfmt provides a convenient way to do this: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#use_field_init_shorthand

### CODE REVIEW

**Comment by carllerche** [comment]
Great :+1:. Is there a way to lint this? Maybe we should setup tokio w/ clippy or something?

**Comment by taiki-e** [comment]
@carllerche 
I think we can use clippy or rustfmt(add `use_field_init_shorthand = true` to `.rustfmt.toml` and run `cargo fmt --  --check`).

Personally, I think it is better to use clippy because it can detect many things. (my recent PRs(#1332, #1333, #1334) are based on clippy).

**Comment by carllerche** [comment]
I would be happy to add clippy to CI.

**Comment by taiki-e** [comment]
May I work on it?

**Comment by carllerche** [comment]
sure!

**Comment by taiki-e** [comment]
Opened #1335.

**Pull request merged**
