### PR TITLE
chore: bump to newer nightly

### PR DESCRIPTION
**Pull request by taiki-e**
cc #1335

### CODE REVIEW

**Comment by taiki-e** [comment]
Seems that the same problem as https://github.com/tokio-rs/tokio/pull/1335#issuecomment-513527214 is happening.

**Comment by taiki-e** [comment]
(I'm trying another version.)

**Comment by LucioFranco** [comment]
I want to say 19th is safe to update too?

**Comment by carllerche** [comment]
@taiki-e I invited you to the team, once you accept, you should be able to squash merge this.

**Comment by taiki-e** [comment]
Thank you for inviting me to the team ❤️ .

**Comment by taiki-e** [comment]
I did not find an issue related to this in rustfmt, but it might have been fixed in the latest nightly (but clippy is not available in the latest nightly).

In any case, I will investigate this a little more (It has not been reproduced locally yet).

**Pull request merged**
