### PR TITLE
feat: Implement AsyncBufReadExt::fill_buf

### PR DESCRIPTION
**Pull request by Marwes**
Adds a future wrapper around `AsyncBufRead::poll_fill_buf` so that it can be used without needing to poll manually. It unfortunately has to use unsafe to forget a lifetime but I hope the comment explains why this is safe.

### CODE REVIEW

**Comment by sfackler** [comment]
The fact that this simple future requires unsafety to munge lifetimes makes me think that the definition of AsyncBufRead needs to change.

**Comment by taiki-e** [comment]
> The fact that this simple future requires unsafety to munge lifetimes makes me think that the definition of AsyncBufRead needs to change.

Probably it will be API like https://github.com/rust-lang/rfcs/pull/1015?

```rust
pub trait AsyncBufRead: AsyncRead {
    /// Attempt to read from the inner reader, and append the data onto the end of
    /// any currently buffered data.
    fn poll_read_into_buf(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<io::Result<usize>>;

    /// Get a read-only view into the buffered data.
    ///
    /// NOTE: This method **will not** do an implicit read if the buffer is empty.
    /// It will just return an empty slice.
    fn get_buf(&self) -> &[u8];

    fn consume(self: Pin<&mut Self>, amt: usize);
}
```

**Comment by sfackler** [comment]
Yeah, that's what I was thinking.

**Comment by Marwes** [comment]
I altered `AsyncBufRead` to the proposed API and left `poll_fill_buf/fill_buf` as default impls based on these new methods (which was easy and does not require any unsafe).

The only downside I can see is that `std::sync::BufRead` can no longer be used to implement (a fake)`AsyncBufRead`

**Comment by carllerche** [comment]
Thanks for doing this! Since @seanmonstar submitted the referenced RFC, I have requested his review on this PR.

**Comment by Darksonn** [comment]
I am closing this PR in favor of refactoring the `AsyncBufRead` trait as described in #2428.

**Pull request closed without merging**
