### PR TITLE
Add a task set

### LINKED ISSUE #3903: Add a `TaskSet`
This issue contains a proposal for a new `TaskSet` type that is able to store a collection of `JoinHandle` values. A sketch of the API can be found below:

```Rust
struct TaskSet<T> {
    ...
}

impl<T> TaskSet<T> {
    pub fn new() -> Self {
        Self::new_with(Handle::current())
    }

    pub fn new_with(handle: Handle) -> Self;

    pub fn spawn<F>(&mut self, task: F)
    where
        F: Future<Output = T>,
        F: Send + 'static,
        T: Send + 'static;

    pub fn len(&self) -> usize;

    /// Wait until one of the tasks finish, then return its return value.
    /// Returns `None` if the `TaskSet` is empty.
    pub fn next_finished(&mut self) -> Option<T>;

    pub fn poll_next_finished(&mut self, cx: &mut Context<'_>) -> Poll<Option<T>>;
}
```

Related: #2478

### PR DESCRIPTION
**Pull request by MikailBag**
## Motivation
Closes #3903

## Solution

I selected a straightforward approach for the first version. However, `try_poll_next_finished` implementation should be definitely optimized for a large amounr of tasks, because currently, TaskSet is effectively quadratic.

Also, I wonder if moving `spawn` method to a clone-able `TaskSetSpawner` type makes more sense.

### CODE REVIEW

**Comment by Darksonn** [comment]
We are going to want an implementation that is not quadratic. Also, the mutex is unnecessary.

**Comment by Darksonn** [comment]
And I don't think we want a `TaskSetSpawner`, but that is a discussion for the issue.

**Comment by MikailBag** [comment]
> We are going to want an implementation that is not quadratic

Ok, I'm going to write one.

I have the following in mind (I _think_ it is similar to FuturesUnordered):
1. Handles are stored in a linked list on the top of Vec, and we separately keep track of holes.
2. Spawning is straightforward.
3. For each task we create a custom waker which knows the id of the task (i.e. position in vector). When woken, waker stores this id in a queue.

I think this will achieve desired linear run time. Does it sound fine?

**Comment by Darksonn** [comment]
In general it is dangerous to start working on a PR before we have finished discussing the design. You risk wasting your time on something that doesn't end up being the implementation we end up wanting.

**Comment by Darksonn** [comment]
Closing since this was implemented in  #4335 instead.

**Pull request closed without merging**
