### PR TITLE
num_cpus="1.0" -> num_cpus="1.8" for tokio

### PR DESCRIPTION
**Pull request by bcko**

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for the PR. Would you mind clarifying the reason to change the dependency version?

**Comment by carllerche** [comment]
I understand that the latest `num_cpus` is most likely better, but it isn't required to use Tokio. The dependency should list the smallest number that is require. Cargo should automatically pull in the greatest version that it can according to semver.

Does this work for you?

**Comment by bcko** [comment]
Cargo didn't automatically pull num_cpus="1.8" for me.  Would adding caret (num_cpus="^1") work better?https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements
I really appreciate your feedback! :)

**Comment by bcko** [comment]
cargo update worked! thank you so much :)

**Pull request closed without merging**
