### PR TITLE
reset woken of outer future after polled

### PR DESCRIPTION
**Pull request by suikammd**
## Motivation

Current implementation does not reset woken flag after polling outer future. This results in outer future being polled again and again which is unnecessary when outer future not ready.

## Solution

Swap woken flag to false at the start of loop.

### CODE REVIEW

**Comment by suikammd** [comment]
> The other PR had a test that a certain future was not polled more than three times. It seems like a test like that could work here without changing the visibility of anything.

What I want to test is woken flag stay false after the outer future was polled

**Comment by Darksonn** [comment]
Please don't force push the PR when you make changes. It's a lot harder to keep track of what changed since I last looked when you do that.

**Comment by suikammd** [comment]
> Please don't force push the PR when you make changes. It's a lot harder to keep track of what changed since I last looked when you do that.

I see, I was worried about too many commits.

**Comment by Darksonn** [comment]
We squash your PR on merge, so that's not a concern.

**Pull request merged**
