### PR TITLE
Add a Condvar-style `wait` to `Notify`

### PR DESCRIPTION
**Pull request by kaimast**
(Opening this as a draft for further discussion on solving #3892)

## Motivation

This addresses the desire for having functionality similar to condition variables in tokio. Regular `Notify::notified` and `Notify::notify_waiters` has the potential for race conditions as they cannot be used in conjunction with a lock,.

## Solution

This adds a new method the `Notify`, instead of introducing a new struct. `Notify::wait` takes a `MutexGuard` and will drop the lock *after* the task has been added to Notify's list of waiters.
When the function succeeds it will re-acquire the lock associated with the `MutexGuard`.

### CODE REVIEW

**Comment by Darksonn** [comment]
The main challenge here is that if the future consumes a `notify_one` token, but then is cancelled before it can reacquire the mutex lock, that wakeup is lost. One way to solve that is to make a new `notify_one` token when it gets cancelled, but this can lead to spurious wakeups which `Notify` currently does not have.

**Comment by kaimast** [comment]
> The main challenge here is that if the future consumes a `notify_one` token, but then is cancelled before it can reacquire the mutex lock, that wakeup is lost. One way to solve that is to make a new `notify_one` token when it gets cancelled, but this can lead to spurious wakeups which `Notify` currently does not have.

The API could also be slightly changed so that returning from wait will not acquire the Mutex, but instead that is something you have to do manually.
That would be different from how std's Condvar works but it should resolve the cancellation issue.

**Comment by Darksonn** [comment]
If you don't make `wait` return a guard, then we don't gain any new features. The only thing you can't already do with `Notify` is to make "consuming permit" and "lock mutex" an atomic operation.

**Comment by Darksonn** [comment]
I'm going to close this. If we are to add condvar-like functionality, then I do not think that it should go on `Notify`. The `Notify` utility does not have spurious wakeups, but I don't think there is a reasonable implementation of condvars without spurious wakeups.

**Comment by kaimast** [comment]
> If you don't make `wait` return a guard, then we don't gain any new features. The only thing you can't already do with `Notify` is to make "consuming permit" and "lock mutex" an atomic operation.

That's the main issue with `Notify` though. There is no way to add yourself to the waiter list while holding a lock.

I do no think a similar issue exist when waking up.

**Comment by kaimast** [comment]
> Actually, that is possible by using [`tokio::sync::futures::Notified::enable`](https://docs.rs/tokio/latest/tokio/sync/futures/struct.Notified.html#method.enable).

Thanks for pointing this out. I have been using `Notified::enable` for a while now and it works as intended.

I was thinking about creating a third-party crate that wraps around `Notify::enable` to provide a condition variable primitive. However, I would still need some kind of `MutexGuard::into_mutex()` method, which drops the lock and returns the underlying Mutex, for that to work. 

Is that something we could add to tokio's API? I will create a pull request if there is some hope for it being merged.

**Comment by Darksonn** [comment]
Tokio already provides a method for obtaining a reference to the mutex: [`tokio::sync::MutexGuard::mutex`][1]. 

[1]: https://docs.rs/tokio/latest/tokio/sync/struct.MutexGuard.html#method.mutex

**Pull request closed without merging**
