### PR TITLE
v0.1.x: continuous disintegration

### PR DESCRIPTION
**Pull request by dekellum**
For now, just seeing if v0.1.x CI fails the way I suspect it will.

### CODE REVIEW

**Comment by dekellum** [comment]
That's novel. Anyway, serde_derive v1.0.99, a dev dep of tokio crate, has MSRV 1.31.0. The minimum rust CI test is only a `cargo check`, which surprisingly doesn't trip up on this.

``` txt
tokio v0.1.22
[dev-dependencies]
├── serde_derive v1.0.99
│   ├── proc-macro2 v1.0.2
│   │   └── unicode-xid v0.2.0
│   ├── quote v1.0.2
│   │   └── proc-macro2 v1.0.2 (*)
│   └── syn v1.0.5
│       ├── proc-macro2 v1.0.2 (*)
│       ├── quote v1.0.2 (*)
│       └── unicode-xid v0.2.0 (*)
```

**Comment by dekellum** [comment]
I was a day off. cc-1.0.42 was just released with MSRV bumped to 1.31.0, by way of edition="2018" (see alexcrichton/cc-rs#439)  which [fails] on our MSRV 1.28 cargo with `cargo check --all`:

``` txt
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.42/Cargo.toml`

Caused by:
  editions are unstable

Caused by:
  feature `edition` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature
```

Its only a transitive dev dependency of the _tokio_ crate, but its a build dependency of _tokio-tls_. Via `cargo tree -i -p cc`:

### tokio-tls
```
cc v1.0.42
[build-dependencies]
└── openssl-sys v0.9.49
    ├── native-tls v0.2.3
    │   └── tokio-tls v0.2.1 (/home/david/src/tokio-0.1/tokio-tls)
    └── openssl v0.10.24
        └── native-tls v0.2.3 (*)
        [dev-dependencies]
        └── tokio-tls v0.2.1 (/home/david/src/tokio-0.1/tokio-tls) (*)
```
### tokio
```
cc v1.0.42
[build-dependencies]
├── miniz-sys v0.1.12
│   └── flate2 v1.0.9
│       [dev-dependencies]
│       └── tokio v0.1.22 (/home/david/src/tokio-0.1/tokio)
└── miniz_oxide_c_api v0.2.3
    └── flate2 v1.0.9 (*)
```

[fails]: https://dev.azure.com/tokio-rs/Tokio/_build/results?buildId=2306&view=logs&jobId=dab7fc15-254b-5b2f-495c-27cce245515f&taskId=8cdf386b-ecdb-539f-ee20-515d05eaa52a&lineStart=63&lineEnd=64&colStart=1&colEnd=1

**Comment by LucioFranco** [comment]
Is it a breaking change to but msrv? seems like cc did it so I guess not?

**Comment by dekellum** [comment]
While such certainly causes many problems for users and downstream maintainers alike, this isn't a PR to change ecosystem attitudes, or even just Tokio's policy, which has in the past introduced intentional MSRV increases in PATCH releases.  ;-)  Tokio would be at some version like 0.17.3, or better yet 2.5.3, if it had made at least MINOR bumps for MSRV increases! 

For now this is just a demonstration that 0.1.x CI is indeed broken again, after working for just 3 weeks after I last fixed it in #1451, and more importantly, tokio-tls-0.2.1 users already have their MSRV effectively raised to 1.31.0 (at least without applying application dependency hacks).

**Comment by dekellum** [comment]
cfg-if 0.1.10 was released yesterday, 2019-9-24, with edition="2018" (alexcrichton/cfg-if@171ba7ff) and thus MSRV 1.31.0.  This is a build dependency of pretty much everything, by way of such dependencies as (crc32fast, crossbeam-*, log, loom, net2, openssl, tempfile, etc.)

So at this point we can safely say that the event horizon of rust 1.31.0 has reached back to tokio 0.1.x.

**Comment by dekellum** [comment]
This draft has outlived its purpose. Closing for now.

**Pull request closed without merging**
