### PR TITLE
Make oneshot::Sender::poll_closed public again

### PR DESCRIPTION
**Pull request by seanmonstar**

### CODE REVIEW

**Review by Darksonn — COMMENTED** [review]
I would prefer to not make it `#[doc(hidden)]`.

**Comment by seanmonstar** [comment]
We can add docs, I just made it doc(hidden) to try to land it with less fuss. :shrug:

**Comment by carllerche** [comment]
I'm fine making this public, but we should include decent API docs w/ an example :) (and not make it doc hidden).

**Comment by Darksonn** [comment]
I submitted a commit with documentation. It also moves the `poll_fn` such that it appears in a better order in the generated documentation.

**Review by carllerche — APPROVED** [review]
:+1: thanks

**Pull request merged**
