### PR TITLE
ci: use latest Valgrind

### PR DESCRIPTION
**Pull request by taiki-e**
debugging slow CI

### CODE REVIEW

**Comment by taiki-e** [comment]
hmm, it's still slow sometimes: 

- 45m https://github.com/tokio-rs/tokio/runs/4674059799?check_suite_focus=true
- 48m https://github.com/tokio-rs/tokio/runs/4674237353?check_suite_focus=true

all runs: https://github.com/tokio-rs/tokio/actions/workflows/stress-test.yml?query=branch%3Ataiki-e%2Fvalgrind

**Comment by Darksonn** [comment]
It also seems like it's complaining about a leak? Is the test not working?

**Comment by taiki-e** [comment]
Oh, we should use --error-exitcode.

https://valgrind.org/docs/manual/manual-core.html#manual-core.erropts

> --error-exitcode=<number> [default: 0]
>
> Specifies an alternative exit code to return if Valgrind reported any errors in the run. When set to the default value (zero), the return value from Valgrind will always be the return value of the process being simulated. When set to a nonzero value, that value is returned instead, if Valgrind detects any errors. This is useful for using Valgrind as part of an automated test suite, since it makes it easy to detect test cases for which Valgrind has reported errors, just by inspecting return codes.

**Comment by Darksonn** [comment]
I did try to add that in the past in #4066, but I missed the stress test apparently.

**Comment by carllerche** [comment]
What's up w/ this PR?

**Comment by carllerche** [comment]
Ah, it is still marked as a draft.

**Review by Darksonn — APPROVED** [review]

**Comment by Noah-Kennedy** [comment]
@taiki-e is this ready for review?

**Review by Noah-Kennedy — APPROVED** [review]

**Pull request merged**
