### PR TITLE
Decrement thread count on thread exit.

### PR DESCRIPTION
**Pull request by jothan**
I hit a problem that after 10 seconds idle, no blocking tasks would
run anymore as all blocking threads exited and the Pool was convinced
that there were still runners available.

Nowhere in the code is num_th decremented. Please make sure the num_idle decrement is correct at that point in the code.

### CODE REVIEW

**Comment by jothan** [comment]
It looks like I duped #1560, but that patch does not decrement the total thread count.

**Comment by jothan** [comment]
I don't know what happened, but I managed to hit a decrement that underflowed num_idle to 2^32-1 with this patch applied.

**Comment by jothan** [comment]
@carllerche Thanks for the review !

**Comment by AnickaBurova** [comment]
I just noticed another issue:
shared.num_idle += 1; is incrementing,
but when the task is executed, we continue 'outer'; and the increment will happen again. And we have one thread but 2 idles!
I think num_idle should be decremented there as well. Please check.

**Comment by jothan** [comment]
@AnickaBurova for the case you are mentionning, if I am not mistaken, the idle count should be decremented by 1 for every wakeup signaled. Have you hit a case in practice where num_idle > num_th ?

**Comment by carllerche** [comment]
Merging master should fix the clippy failure (#1569).

**Comment by carllerche** [comment]
I took the liberty of merging master to get this fix in sooner :+1:

**Pull request merged**
