### PR TITLE
trace-core: Make `with_default` more flexible

### PR DESCRIPTION
**Pull request by hawkw**
## Motivation

Currently, `tokio-trace` provides two separate functions for setting the
defautl dispatcher. `tokio-trace-core` defines the
`dispatcher::with_default` function, which takes an `&Dispatch`.
`tokio-trace` re-exports this function, but also defines a separate
`subscriber::with_default` function, which takes a `T: Subscriber`,
wraps it as a `Dispatch`, and then calls `dispatcher::with_default`.
This is intended as a convenience method, but having two separate
functions can be confusing.

## Solution

This branch changes `tokio_trace_core::dispatcher::with_default` to take
an `impl Into<Dispatch>`, and adds an implementation of `Into<Dispatch>`
for `&'a Dispatch` that clones the dispatcher. This means that
`dispatcher::with_default` can now be invoked with a `Subscriber`, a
`Dispatch`, _or_ a `&Dispatch`, obviating the need for a separate
`subscriber::with_default`.

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### CODE REVIEW

**Comment by carllerche** [comment]
I would prefer to avoid the generic in `-core`. Instead, can you not re-export the `core` fn in `tokio-trace`?

**Comment by hawkw** [comment]
@carllerche ah, good call --- we can just move the generic function to `tokio-trace` and not re-export the `core` function.

**Comment by carllerche** [comment]
IMO we should not be optimizing for users to call `with_default`. Requiring the call is a temporary hack for early adopters who really want to try out tokio-trace. In the medium term, everything will be built into the Tokio runtime.

Given this, I believe the API should stay simple.

(I'm leaving the final decision to @hawkw)

**Comment by LucioFranco** [comment]
@carllerche I believe though that we should only expose on with_default and a Into dispatcher makes this more explicit. I do believe we should support use cases that are outside of the runtime usecase, for example, at work we manually create a runtime and dont treat our application as one large future, but we still want to be able to use our subscriber/dispatcher for loading config for example.

**Comment by hawkw** [comment]
While I'm not particularly attached to this particular PR being merged. I do think it's worth noting that I've heard from a decent number of folks interested in using `tokio-trace` outside of the `tokio` runtime, and I think it's worth thinking about ergonomics in cases where a runtime isn't managing everything.

**Comment by hawkw** [comment]
I'm going to hold off on this for core v0.2, at least.

**Comment by carllerche** [comment]
Should this stay open?

**Pull request closed without merging**
