### PR TITLE
Expose signal from net as a feature

### PR DESCRIPTION
**Pull request by dbcfd**
## Motivation
Address #1490 

## Solution
Add a feature to main tokio crate for signal.

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for doing this work :+1:

I believe the plan, based on [this](https://github.com/tokio-rs/tokio/issues/1243#issuecomment-522277980) thread, is to only expose `ctrl_c()` from `tokio::signal` (at least initially).

Would you be able to update the PR to only expose `ctrl_c()`?

**Comment by dbcfd** [comment]
Should I also expose unix mod behind a cfg unix check?

**Comment by carllerche** [comment]
@ipetkov thoughts?

**Comment by ipetkov** [comment]
I’d say let’s punt on the Unix additions for now. IIRC the rest of the tokio crate doesn’t reexport *everything* of the subcrates, and sticking to the platform agnostic APIs is a safe initial bet. 

We can always add the Unix export later in a backwards compatible manner!

(If anyone disagrees or has other thoughts feel free to chime in on #1243 !)

--Ivan

**Comment by dbcfd** [comment]
@ipetkov Only ctrl_c is exposed in tokio::net::signal via feature flag signal.

**Pull request merged**
