### PR TITLE
fmt: Ignore the target dir when formatting

### PR DESCRIPTION
**Pull request by hi-rustin**
Signed-off-by: hi-rustin <rustin.liu@gmail.com>

## Motivation

Ignore the target folder when formatting, it always gets false positives.

<details>

```log
➜  tokio git:(master) rustfmt --check --edition 2018 $(find . -name '*.rs' -print)   
Diff in /Users/rustin/ClionProjects/tokio/target/debug/build/proc-macro-nested-bbbacb4578d95e8a/out/count.rs at line 1:
 #[doc(hidden)]
 #[macro_export]
 macro_rules! count {
-    () => { proc_macro_call_0!() };
-    (!) => { proc_macro_call_1!() };
-    (!!) => { proc_macro_call_2!() };
-    (!!!) => { proc_macro_call_3!() };
-    (!!!!) => { proc_macro_call_4!() };
-    (!!!!!) => { proc_macro_call_5!() };
-    (!!!!!!) => { proc_macro_call_6!() };
-    (!!!!!!!) => { proc_macro_call_7!() };
-    (!!!!!!!!) => { proc_macro_call_8!() };
-    (!!!!!!!!!) => { proc_macro_call_9!() };
-    (!!!!!!!!!!) => { proc_macro_call_10!() };
-    (!!!!!!!!!!!) => { proc_macro_call_11!() };
-    (!!!!!!!!!!!!) => { proc_macro_call_12!() };
-    (!!!!!!!!!!!!!) => { proc_macro_call_13!() };
-    (!!!!!!!!!!!!!!) => { proc_macro_call_14!() };
-    (!!!!!!!!!!!!!!!) => { proc_macro_call_15!() };
-    (!!!!!!!!!!!!!!!!) => { proc_macro_call_16!() };
-    (!!!!!!!!!!!!!!!!!) => { proc_macro_call_17!() };
-    (!!!!!!!!!!!!!!!!!!) => { proc_macro_call_18!() };
-    (!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_19!() };
-    (!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_20!() };
-    (!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_21!() };
-    (!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_22!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_23!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_24!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_25!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_26!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_27!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_28!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_29!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_30!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_31!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_32!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_33!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_34!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_35!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_36!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_37!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_38!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_39!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_40!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_41!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_42!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_43!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_44!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_45!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_46!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_47!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_48!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_49!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_50!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_51!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_52!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_53!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_54!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_55!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_56!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_57!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_58!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_59!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_60!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_61!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_62!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_63!() };
-    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => { proc_macro_call_64!() };
+    () => {
+        proc_macro_call_0!()
+    };
+    (!) => {
+        proc_macro_call_1!()
+    };
+    (!!) => {
+        proc_macro_call_2!()
+    };
+    (!!!) => {
+        proc_macro_call_3!()
+    };
+    (!!!!) => {
+        proc_macro_call_4!()
+    };
+    (!!!!!) => {
+        proc_macro_call_5!()
+    };
+    (!!!!!!) => {
+        proc_macro_call_6!()
+    };
+    (!!!!!!!) => {
+        proc_macro_call_7!()
+    };
+    (!!!!!!!!) => {
+        proc_macro_call_8!()
+    };
+    (!!!!!!!!!) => {
+        proc_macro_call_9!()
+    };
+    (!!!!!!!!!!) => {
+        proc_macro_call_10!()
+    };
+    (!!!!!!!!!!!) => {
+        proc_macro_call_11!()
+    };
+    (!!!!!!!!!!!!) => {
+        proc_macro_call_12!()
+    };
+    (!!!!!!!!!!!!!) => {
+        proc_macro_call_13!()
+    };
+    (!!!!!!!!!!!!!!) => {
+        proc_macro_call_14!()
+    };
+    (!!!!!!!!!!!!!!!) => {
+        proc_macro_call_15!()
+    };
+    (!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_16!()
+    };
+    (!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_17!()
+    };
+    (!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_18!()
+    };
+    (!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_19!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_20!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_21!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_22!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_23!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_24!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_25!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_26!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_27!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_28!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_29!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_30!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_31!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_32!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_33!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_34!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_35!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_36!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_37!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_38!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_39!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_40!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_41!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_42!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_43!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_44!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_45!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_46!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_47!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_48!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_49!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_50!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_51!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_52!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_53!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_54!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_55!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_56!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_57!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_58!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_59!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_60!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_61!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_62!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_63!()
+    };
+    (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) => {
+        proc_macro_call_64!()
+    };
     ($(!)+) => {
         compile_error! { "this macro does not support >64 nested macro invocations" }
     };
➜  tokio git:(master) 
```

</details>

## Solution

Ignore the target dir when formatting.

### CODE REVIEW

**Comment by taiki-e** [comment]
How about using `git ls-files` instead of `find`?

```sh
rustfmt --check $(git ls-files '*.rs')
```

https://github.com/rust-lang/futures-rs/blob/0.3.15/tools/fmt.sh#L27

**Comment by hi-rustin** [comment]
> How about using `git ls-files` instead of `find`?
> 
> ```shell
> rustfmt --check $(git ls-files '*.rs')
> ```
> 
> https://github.com/rust-lang/futures-rs/blob/0.3.15/tools/fmt.sh#L27

```log
➜  tokio git:(master) ✗ rustfmt --check --edition=2018 $(git ls-files '*.rs')
Diff in /Users/rustin/ClionProjects/tokio/tokio/src/net/tcp/socket.rs at line 117:
     /// }
     /// ```
     pub fn new_v4() -> io::Result<TcpSocket> {
-            let inner = mio::net::TcpSocket::new_v4()?;
+        let inner = mio::net::TcpSocket::new_v4()?;
         Ok(TcpSocket { inner })
     }
 
Diff in /Users/rustin/ClionProjects/tokio/tokio/src/net/tcp/socket.rs at line 117:
     /// }
     /// ```
     pub fn new_v4() -> io::Result<TcpSocket> {
-            let inner = mio::net::TcpSocket::new_v4()?;
+        let inner = mio::net::TcpSocket::new_v4()?;
         Ok(TcpSocket { inner })
     }
 
➜  tokio git:(master) ✗ 
```

It looks like it will produce two outputs.

**Comment by taiki-e** [comment]
Hmm, that seems to be a bug in rustfmt. I can reproduce the same thing with both `find` and `git ls-file`.

```console
❯ rustfmt --check --edition 2018 $(find . -path './target' -prune -o -name '*.rs' -print)
Diff in /Users/taiki/projects/tokio/tokio/src/net/tcp/socket.rs at line 117:
     /// }
     /// ```
     pub fn new_v4() -> io::Result<TcpSocket> {
-            let inner = mio::net::TcpSocket::new_v4()?;
+        let inner = mio::net::TcpSocket::new_v4()?;
         Ok(TcpSocket { inner })
     }
 
Diff in /Users/taiki/projects/tokio/tokio/src/net/tcp/socket.rs at line 117:
     /// }
     /// ```
     pub fn new_v4() -> io::Result<TcpSocket> {
-            let inner = mio::net::TcpSocket::new_v4()?;
+        let inner = mio::net::TcpSocket::new_v4()?;
         Ok(TcpSocket { inner })
     }
``` 

```console
❯ rustfmt --check --edition=2018 -- $(git ls-files '*.rs') 
Diff in /Users/taiki/projects/tokio/tokio/src/net/tcp/socket.rs at line 117:
     /// }
     /// ```
     pub fn new_v4() -> io::Result<TcpSocket> {
-            let inner = mio::net::TcpSocket::new_v4()?;
+        let inner = mio::net::TcpSocket::new_v4()?;
         Ok(TcpSocket { inner })
     }
 
Diff in /Users/taiki/projects/tokio/tokio/src/net/tcp/socket.rs at line 117:
     /// }
     /// ```
     pub fn new_v4() -> io::Result<TcpSocket> {
-            let inner = mio::net::TcpSocket::new_v4()?;
+        let inner = mio::net::TcpSocket::new_v4()?;
         Ok(TcpSocket { inner })
     }
```

**Comment by hi-rustin** [comment]
@taiki-e It does look like a bug in rustfmt!

```log
➜  tokio git:(master) ✗ rustfmt --check --edition 2018 $(find . -path './target' -prune -o -name '*.rs' -print)
Diff in /Users/rustin/ClionProjects/tokio/tokio-macros/src/lib.rs at line 19:
 extern crate proc_macro;
 
 mod entry;
-    mod select;
+mod select;
 
 use proc_macro::TokenStream;
 
➜  tokio git:(master) ✗ 
```

**Comment by hi-rustin** [comment]
> How about using `git ls-files` instead of `find`?

Addressed!

**Review by taiki-e — APPROVED** [review]
Thanks!

**Review by Noah-Kennedy — APPROVED** [review]

**Pull request merged**
