### PR TITLE
test: implement safe abstraction using the `Wake` trait

### PR DESCRIPTION
**Pull request by nurmohammed840**

### CODE REVIEW

**Comment by Darksonn** [comment]
This seems to contain two independent changes: using the `Wake` trait and a new `block_on` method. Could you explain what you're trying to do?

**Comment by nurmohammed840** [comment]
[Wake](https://doc.rust-lang.org/std/task/trait.Wake.html) trait provides a safe abstraction for creating [Waker](https://doc.rust-lang.org/std/task/struct.Waker.html) from an `Arc` pointer data:

https://github.com/tokio-rs/tokio/blob/9cc4a81678ffb423cf89c12b08241272c1b6ecb1/tokio-test/src/task.rs#L59-L61

This reduces both boilerplate and, more importantly `unsafe` code.
 
---

I'm really surprised that there isn't a `block_on` function:
Although original implementation do support this:

https://github.com/tokio-rs/tokio/blob/9cc4a81678ffb423cf89c12b08241272c1b6ecb1/tokio-test/src/task.rs#L209-L212

https://github.com/tokio-rs/tokio/blob/9cc4a81678ffb423cf89c12b08241272c1b6ecb1/tokio-test/src/task.rs#L245-L247

Original implementation has `Condvar`, But it isn't used anywhere.
Also the name `ThreadWaker` implies that it's used to wake a sleeping thread, but no thread is actually sleeping (because there is no `block_on`), I believe the author may have forgotten to include `block_on` function.

This is my main reason to add `block_on`

It could also be useful as a basic future executor, similar to [futures::executor::block_on](https://docs.rs/futures/latest/futures/executor/fn.block_on.html)

**Comment by Darksonn** [comment]
We use `tokio_test::task::spawn` quite a lot in our test suite, and we don't need it to include a `block_on` there. Usually, it's used to manually call `poll` in a convenient manner. What are you trying to use it for?

**Comment by nurmohammed840** [comment]
This could be useful outside of Tokio test suites for general-purpose future execution.
Most test cases don't require an **I/O event loop** or **Timer**

It's also well-suited for benchmarking asynchronous code due to its lightweight nature. [Here is one example](https://github.com/nurmohammed840/async-gen/tree/master/benches)

---

Most importantly original implementation has already support for it.

Maybe we should consider replacing entire `wake()` function with just single `AtomicBool::store` operation, if we decide to drop `block_on` support.

https://github.com/tokio-rs/tokio/blob/161b8c80d58a4a070c7f41db18d43ea258737db7/tokio-test/src/task.rs#L230

**Comment by Darksonn** [comment]
> Maybe we should consider replacing entire `wake()` function with just single `AtomicBool::store` operation, if we decide to drop `block_on` support.

Right now, `Task<F>` implements the `Future` trait and can be passed to `tokio::runtime::Runtime::block_on`. The change you suggest would break that, as wakeups would no longer be sent.

> It's also well-suited for benchmarking asynchronous code due to its lightweight nature.

It can't benchmark anything other than pure computation. At that point, why is it async at all? Using async in benchmarks is fraught with issues and very difficult to do right.

More importantly, the purpose of `tokio_test::task::spawn` is _not_ to be useful in benchmarks. Its purpose is to be useful for testing that async synchronization primitives send wakeups at the right times. Don't give it additional purposes.

> This could be useful outside of Tokio test suites for general-purpose future execution.

Why should we make `tokio_test::task::spawn` be useful for things other than writing tests? Writing tests is the entire purpose of the tokio-test crate. This crate is the *wrong* place for general-purpose future execution. If people want that, they can create a Tokio runtime. If they don't want IO/timer drivers, they can create a Tokio runtime without IO/timer drivers. Or they can use `futures::executor::block_on`. Telling them to use the tokio-test crate in that case makes no sense.

---

As a more general concern, your PR makes two different changes:

* Use the `Wake` trait to get rid of unsafe.
* Add a `block_on` function.

I'm skeptical about adding a `block_on`, but even if we do that, these two independent changes should not be in the same PR.

**Pull request closed without merging**
