### PR TITLE
chore: update rust-toolchain to use beta

### PR DESCRIPTION
**Pull request by taiki-e**
## Motivation

Our CI is now running on beta.

### CODE REVIEW

**Comment by LucioFranco** [comment]
@taiki-e why not pin it to beta?

**Comment by taiki-e** [comment]
@LucioFranco I don't have a strong opinion, but I thought rust-toolchain is for pinning a breakable nightly version.

**Comment by LucioFranco** [comment]
@taiki-e yeah it is, but it can be used for stable versions. We use it at work to update our rust toolchain https://github.com/timberio/vector/blob/master/rust-toolchain

**Comment by taiki-e** [comment]
@LucioFranco Oh, interesting. Does it work even if it's running CI in multiple versions? (I think master branch to do it in the future like [v0.1.0 branch](https://github.com/tokio-rs/tokio/blob/v0.1.x/azure-pipelines.yml).)

**Comment by LucioFranco** [comment]
@taiki-e to swap the toolchain out we manually do `mv rust-toolchain rust-toolchain.bak` which is easy to do on CI.

**Comment by carllerche** [comment]
I would opt to keep it until it lands on stable. Mostly because, w/ the file, `cargo x` just works.

That said, I greatly appreciate all the work you are doing keeping up w/ the cleanup tasks :+1:

**Comment by taiki-e** [comment]
> Mostly because, w/ the file, `cargo x` just works.

It makes sense. Updated.

**Pull request merged**
