### PR TITLE
net: introduce split on UnixDatagram

### PR DESCRIPTION
**Pull request by cssivision**
fix issue https://github.com/tokio-rs/tokio/issues/2551 

this pr can be closed if this is merged. https://github.com/tokio-rs/tokio/pull/1757

### CODE REVIEW

**Comment by cssivision** [comment]
> I only had a quick look, but three things came to mind:
> 
> 1. What about a by-ref split like in `TcpStream`?
> 2. What about naming? `TcpStream` calls its owned split `into_split`.
> 3. The owned tcp split closes the stream when the writer is dropped. Should we also do that here?
> 
> We currently have different naming conventions on `split`/`into_split` that we can't fix until v0.3 due to backwards compatibility. Still doesn't hurt to choose what we intend to converge on in v0.3 here.
> 
> See also the PR for owned split on TCP streams: #2270.

thanks for reviewing this pr. keep consistent with `TcpStream`'s `into_split` is a good idea. I can add `into_split` for `UdpSocket` and `UnixStream` and `split` for `UnixDatagram` if it will be accepted.

**Comment by Darksonn** [comment]
The issue with `UdpSocket` and `UnixStream` is that the function they already have called `split` does what `TcpStream`'s `into_split` does, and that can only be fixed when we move to v0.3.

**Comment by cssivision** [comment]
it's ok to fix `UnixStream ` and `UdpSocket ` when reach v0.3.  I will add `split` to `UnixDatagram`.

**Comment by cssivision** [comment]
activate

**Pull request merged**
